import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    "nav.home": "Accueil",
    "nav.solutions": "Nos Solutions",
    "nav.demo": "Démo",
    "nav.contact": "Contact",
    "nav.sectors": "Secteurs",
    "nav.getStarted": "Démarrer maintenant",
    "nav.hub.offer": "Ce qu'on fait",
    "nav.hub.showcase": "Réalisations",
    "nav.hub.talk": "Parler à Botler",
    "nav.hub.book": "Rendez-vous",
    
    // Sectors
    "sector.tourism": "Tourisme",
    "sector.viticulture": "Viticulture",
    "sector.restaurants": "Restaurants",
    "sector.bakery": "Boulangerie",
    "sector.realEstate": "Immobilier",
    "sector.accommodation": "Hébergements",

    // Sector Pages - Tourisme
    "sector.tourisme.badge": "Solution Tourisme",
    "sector.tourisme.title1": "Botler™ pour le",
    "sector.tourisme.highlight": "Tourisme",
    "sector.tourisme.description": "Transformez l'expérience de vos visiteurs avec un assistant virtuel disponible 24h/24, capable de répondre à toutes leurs questions sur votre destination.",
    "sector.tourisme.challenge1": "Visiteurs qui partent sans réponse à leurs questions",
    "sector.tourisme.challenge2": "Équipe débordée pendant les pics de saison",
    "sector.tourisme.challenge3": "Difficulté à communiquer en plusieurs langues",
    "sector.tourisme.challenges.title1": "Les défis du",
    "sector.tourisme.challenges.highlight": "secteur touristique",
    "sector.tourisme.challenges.description": "Le tourisme fait face à des enjeux uniques de disponibilité et de multilinguisme.",
    "sector.tourisme.solutions.title1": "Nos",
    "sector.tourisme.solutions.highlight": "solutions",
    "sector.tourisme.solution1.title": "Assistant multilingue",
    "sector.tourisme.solution1.desc": "Répondez à vos visiteurs dans leur langue, automatiquement.",
    "sector.tourisme.solution2.title": "Disponible 24h/24",
    "sector.tourisme.solution2.desc": "Ne perdez plus de visiteurs, même en dehors des heures d'ouverture.",
    "sector.tourisme.solution3.title": "Recommandations personnalisées",
    "sector.tourisme.solution3.desc": "Suggérez les meilleures activités selon les préférences de chacun.",
    "sector.tourisme.stat1.value": "+40%",
    "sector.tourisme.stat1.label": "Satisfaction visiteurs",
    "sector.tourisme.stat2.value": "15h",
    "sector.tourisme.stat2.label": "Économisées par semaine",
    "sector.tourisme.stat3.value": "24/7",
    "sector.tourisme.stat3.label": "Disponibilité",
    "sector.tourisme.video.title": "Voir Botler™ en action",
    "sector.tourisme.testimonial.text": "Botler™ a révolutionné notre accueil visiteur. +40% de satisfaction et une disponibilité 24h/24 qui fait la différence.",
    "sector.tourisme.testimonial.author": "Office de Tourisme de Bordeaux",
    "sector.tourisme.testimonial.role": "Directeur",

    // Sector Pages - Viticulture
    "sector.viticulture.badge": "Solution Viticulture",
    "sector.viticulture.title1": "Botler™ pour la",
    "sector.viticulture.highlight": "Viticulture",
    "sector.viticulture.description": "Votre sommelier virtuel conseille vos visiteurs sur les accords mets-vins et présente vos cuvées avec passion.",
    "sector.viticulture.challenge1": "Clients qui hésitent sans conseils personnalisés",
    "sector.viticulture.challenge2": "Manque de temps pour accueillir chaque visiteur",
    "sector.viticulture.challenge3": "Ventes perdues en dehors des heures d'ouverture",
    "sector.viticulture.challenges.title1": "Les défis de la",
    "sector.viticulture.challenges.highlight": "viticulture",
    "sector.viticulture.challenges.description": "Le monde du vin nécessite expertise et disponibilité pour conseiller les clients.",
    "sector.viticulture.solutions.title1": "Nos",
    "sector.viticulture.solutions.highlight": "solutions",
    "sector.viticulture.solution1.title": "Sommelier virtuel",
    "sector.viticulture.solution1.desc": "Conseils œnologiques personnalisés pour chaque visiteur.",
    "sector.viticulture.solution2.title": "Réservation de visites",
    "sector.viticulture.solution2.desc": "Gérez automatiquement les demandes de dégustation.",
    "sector.viticulture.solution3.title": "Présentation des cuvées",
    "sector.viticulture.solution3.desc": "Mettez en valeur votre production avec passion.",
    "sector.viticulture.stat1.value": "+35%",
    "sector.viticulture.stat1.label": "Ventes en ligne",
    "sector.viticulture.stat2.value": "+50%",
    "sector.viticulture.stat2.label": "Réservations visites",
    "sector.viticulture.stat3.value": "8",
    "sector.viticulture.stat3.label": "Langues supportées",
    "sector.viticulture.video.title": "Découvrez notre sommelier virtuel",
    "sector.viticulture.testimonial.text": "Nos ventes en ligne ont augmenté de 35% grâce aux conseils personnalisés de Botler™.",
    "sector.viticulture.testimonial.author": "Domaine des Vignes",
    "sector.viticulture.testimonial.role": "Propriétaire",

    // Sector Pages - Restaurants
    "sector.restaurants.badge": "Solution Restaurants",
    "sector.restaurants.title1": "Botler™ pour les",
    "sector.restaurants.highlight": "Restaurants",
    "sector.restaurants.description": "Votre meilleur assistant restaurateur 24h/24 pour gérer les réservations et présenter votre carte.",
    "sector.restaurants.challenge1": "Appels manqués = réservations perdues",
    "sector.restaurants.challenge2": "Questions répétitives sur le menu et allergènes",
    "sector.restaurants.challenge3": "Gestion du rush pendant les services",
    "sector.restaurants.challenges.title1": "Les défis de la",
    "sector.restaurants.challenges.highlight": "restauration",
    "sector.restaurants.challenges.description": "La restauration demande réactivité et organisation pour satisfaire chaque client.",
    "sector.restaurants.solutions.title1": "Nos",
    "sector.restaurants.solutions.highlight": "solutions",
    "sector.restaurants.solution1.title": "Gestion des réservations",
    "sector.restaurants.solution1.desc": "Acceptez les réservations 24h/24, même pendant le service.",
    "sector.restaurants.solution2.title": "Présentation du menu",
    "sector.restaurants.solution2.desc": "Répondez aux questions sur les plats et allergènes.",
    "sector.restaurants.solution3.title": "Commandes à emporter",
    "sector.restaurants.solution3.desc": "Facilitez les commandes en click & collect.",
    "sector.restaurants.stat1.value": "+50%",
    "sector.restaurants.stat1.label": "Réservations",
    "sector.restaurants.stat2.value": "0",
    "sector.restaurants.stat2.label": "Appels manqués",
    "sector.restaurants.stat3.value": "5min",
    "sector.restaurants.stat3.label": "Temps de réponse moyen",
    "sector.restaurants.video.title": "Botler™ en restauration",
    "sector.restaurants.testimonial.text": "Nos réservations ont augmenté de 50% grâce à la disponibilité permanente de Botler™.",
    "sector.restaurants.testimonial.author": "Restaurant Le Gourmet",
    "sector.restaurants.testimonial.role": "Chef propriétaire",

    // Sector Pages - Boulangerie
    "sector.boulangerie.badge": "Solution Boulangerie",
    "sector.boulangerie.title1": "Botler™ pour la",
    "sector.boulangerie.highlight": "Boulangerie",
    "sector.boulangerie.description": "Le vendeur virtuel idéal pour présenter vos produits et prendre les commandes.",
    "sector.boulangerie.challenge1": "File d'attente qui décourage les clients",
    "sector.boulangerie.challenge2": "Commandes spéciales difficiles à gérer",
    "sector.boulangerie.challenge3": "Produits non vendus en fin de journée",
    "sector.boulangerie.challenges.title1": "Les défis de la",
    "sector.boulangerie.challenges.highlight": "boulangerie",
    "sector.boulangerie.challenges.description": "La boulangerie artisanale doit conjuguer qualité et efficacité.",
    "sector.boulangerie.solutions.title1": "Nos",
    "sector.boulangerie.solutions.highlight": "solutions",
    "sector.boulangerie.solution1.title": "Catalogue produits",
    "sector.boulangerie.solution1.desc": "Présentez tous vos pains et viennoiseries.",
    "sector.boulangerie.solution2.title": "Prise de commandes",
    "sector.boulangerie.solution2.desc": "Commandes en ligne pour retrait en boutique.",
    "sector.boulangerie.solution3.title": "Horaires et disponibilités",
    "sector.boulangerie.solution3.desc": "Informez sur les produits disponibles en temps réel.",
    "sector.boulangerie.stat1.value": "+30%",
    "sector.boulangerie.stat1.label": "Commandes en ligne",
    "sector.boulangerie.stat2.value": "-20%",
    "sector.boulangerie.stat2.label": "Invendus",
    "sector.boulangerie.stat3.value": "100%",
    "sector.boulangerie.stat3.label": "Clients satisfaits",
    "sector.boulangerie.video.title": "Botler™ en boulangerie",
    "sector.boulangerie.testimonial.text": "Les commandes en ligne ont augmenté de 30% et nos invendus ont diminué de 20%.",
    "sector.boulangerie.testimonial.author": "Boulangerie du Coin",
    "sector.boulangerie.testimonial.role": "Artisan boulanger",

    // Sector Pages - Immobilier
    "sector.immobilier.badge": "Solution Immobilier",
    "sector.immobilier.title1": "Botler™ pour l'",
    "sector.immobilier.highlight": "Immobilier",
    "sector.immobilier.description": "Votre agent virtuel pour qualifier vos prospects et présenter vos biens 24h/24.",
    "sector.immobilier.challenge1": "Prospects non qualifiés qui font perdre du temps",
    "sector.immobilier.challenge2": "Demandes d'information en dehors des heures de bureau",
    "sector.immobilier.challenge3": "Visites inutiles pour des biens non adaptés",
    "sector.immobilier.challenges.title1": "Les défis de l'",
    "sector.immobilier.challenges.highlight": "immobilier",
    "sector.immobilier.challenges.description": "L'immobilier nécessite réactivité et qualification précise des prospects.",
    "sector.immobilier.solutions.title1": "Nos",
    "sector.immobilier.solutions.highlight": "solutions",
    "sector.immobilier.solution1.title": "Qualification prospects",
    "sector.immobilier.solution1.desc": "Identifiez les acheteurs sérieux automatiquement.",
    "sector.immobilier.solution2.title": "Présentation des biens",
    "sector.immobilier.solution2.desc": "Répondez aux questions sur chaque propriété.",
    "sector.immobilier.solution3.title": "Prise de rendez-vous",
    "sector.immobilier.solution3.desc": "Planifiez les visites directement dans votre agenda.",
    "sector.immobilier.stat1.value": "+45%",
    "sector.immobilier.stat1.label": "Contacts qualifiés",
    "sector.immobilier.stat2.value": "2x",
    "sector.immobilier.stat2.label": "Plus de visites utiles",
    "sector.immobilier.stat3.value": "24/7",
    "sector.immobilier.stat3.label": "Disponibilité",
    "sector.immobilier.video.title": "Botler™ en immobilier",
    "sector.immobilier.testimonial.text": "Nos contacts qualifiés ont augmenté de 45% et nos visites sont beaucoup plus efficaces.",
    "sector.immobilier.testimonial.author": "Agence Immo Plus",
    "sector.immobilier.testimonial.role": "Directeur d'agence",

    // Sector Pages - Hébergements
    "sector.hebergements.badge": "Solution Hébergements",
    "sector.hebergements.title1": "Botler™ pour les",
    "sector.hebergements.highlight": "Hébergements",
    "sector.hebergements.description": "Votre concierge virtuel pour accompagner vos clients voyageurs avant, pendant et après leur séjour.",
    "sector.hebergements.challenge1": "Questions répétitives des clients (WiFi, check-in...)",
    "sector.hebergements.challenge2": "Demandes en dehors des heures de réception",
    "sector.hebergements.challenge3": "Difficulté à personnaliser l'expérience client",
    "sector.hebergements.challenges.title1": "Les défis de l'",
    "sector.hebergements.challenges.highlight": "hébergement",
    "sector.hebergements.challenges.description": "L'hébergement demande disponibilité et personnalisation pour chaque voyageur.",
    "sector.hebergements.solutions.title1": "Nos",
    "sector.hebergements.solutions.highlight": "solutions",
    "sector.hebergements.solution1.title": "Informations séjour",
    "sector.hebergements.solution1.desc": "Répondez aux questions sur le WiFi, parking, check-in...",
    "sector.hebergements.solution2.title": "Services disponibles",
    "sector.hebergements.solution2.desc": "Présentez le petit-déjeuner, spa, room service...",
    "sector.hebergements.solution3.title": "Recommandations locales",
    "sector.hebergements.solution3.desc": "Suggérez restaurants, activités et sites à visiter.",
    "sector.hebergements.stat1.value": "+35%",
    "sector.hebergements.stat1.label": "Réservations directes",
    "sector.hebergements.stat2.value": "+40%",
    "sector.hebergements.stat2.label": "Satisfaction client",
    "sector.hebergements.stat3.value": "90%",
    "sector.hebergements.stat3.label": "Questions résolues",
    "sector.hebergements.video.title": "Botler™ pour l'hébergement",
    "sector.hebergements.testimonial.text": "Botler™ a révolutionné notre accueil. +40% de satisfaction et une disponibilité 24h/24.",
    "sector.hebergements.testimonial.author": "Hôtel du Phare",
    "sector.hebergements.testimonial.role": "Directeur",

    // Home — Hero (relift 2026-08)
    "home.hero.cta1": "Voir les démos",
    "home.hero.cta2": "Récupérez mon chatbot",
    "home.hero.h1Pre": "On construit vos sites, vos apps et les",
    "home.hero.h1Highlight": "agents IA",
    "home.hero.h1Post": "qui parlent à vos clients.",
    "home.hero.subtitle": "Sites, boutiques en ligne, applications et agents IA — conçus avec l'IA, livrés en quelques jours.",
    "home.hero.manifesto": "On montre ce qu'on sait faire. On ne le raconte pas.",

    // Home — Boutons partagés (cartes d'offre à deux états, hero, CTA finale)
    "home.cta.talkToBotler": "Parler à Botler",
    "home.cta.bookMeeting": "Prendre un rendez-vous",
    "home.cta.viewPage": "Voir la page",

    // Home — Botler en direct (agent intégré au hero)
    "home.botlerLive.eyebrow": "Botler en direct",
    "home.botlerLive.title": "Parlez-lui, maintenant.",
    "home.botlerLive.description": "Botler répond en direct à vos questions sur nos sites, nos apps et nos agents IA. Écrivez, ou activez le micro pour lui parler à voix haute.",

    // Home — Ce qu'on sait faire (4 familles, §6)
    "home.offer.eyebrow": "Ce qu'on sait faire",
    "home.offer.title": "Quatre façons de vous faire gagner du temps.",
    "home.offer.familyA.title": "Sites & commerce en ligne",
    "home.offer.familyA.benefit": "Un site avec son agent IA intégré, prêt à vendre.",
    "home.offer.familyB.title": "Agents IA cross-canal",
    "home.offer.familyB.benefit": "Un seul agent, partout où vos clients vous cherchent.",
    "home.offer.familyC.title": "Apps & plateformes",
    "home.offer.familyC.benefit": "Applications, espaces client et tableaux de bord sur-mesure.",
    "home.offer.familyD.title": "Studios & formats IA",
    "home.offer.familyD.benefit": "Des formats IA pensés et produits de bout en bout.",
    "home.offer.aio.text": "Botler travaille aussi votre visibilité dans les réponses des IA (Google AI Overview, Perplexity, ChatGPT, Claude).",

    // Home — Comment on travaille
    "home.howWeWork.eyebrow": "Comment on travaille",
    "home.howWeWork.title": "Trois étapes, pas plus.",
    "home.howWeWork.step1.title": "On cadre",
    "home.howWeWork.step1.desc": "Un échange avec Botler ou l'équipe pour cerner votre besoin réel.",
    "home.howWeWork.step2.title": "On construit",
    "home.howWeWork.step2.desc": "Site, app ou agent, conçu avec l'IA et vérifié par l'équipe.",
    "home.howWeWork.step3.title": "On livre",
    "home.howWeWork.step3.desc": "En quelques jours, pas en plusieurs mois.",

    // Home — Ce que nos agents ne font jamais
    "home.boundaries.eyebrow": "Ce que nos agents ne font jamais",
    "home.boundaries.title": "L'honnêteté avant tout.",
    "home.boundaries.item1.title": "Zéro invention",
    "home.boundaries.item1.desc": "Nos agents n'inventent jamais une fonctionnalité, un prix ou une disponibilité.",
    "home.boundaries.item2.title": "Pas de fausse promesse",
    "home.boundaries.item2.desc": "On décrit ce que l'outil fait, jamais un résultat business garanti.",
    "home.boundaries.item3.title": "Transfert à un humain",
    "home.boundaries.item3.desc": "Dès que ça dépasse ses compétences, l'agent passe la main à l'équipe.",

    // Home — Rendez-vous
    "home.booking.eyebrow": "Rendez-vous",
    "home.booking.title": "Réservez un créneau.",
    "home.booking.description": "Choisissez un horaire qui vous convient, on prend le temps de comprendre votre projet.",
    "home.booking.fallback": "La prise de rendez-vous en ligne arrive bientôt. En attendant, écrivez-nous.",

    // Home — Données & sécurité
    "home.dataSecurity.eyebrow": "Données & sécurité",
    "home.dataSecurity.title": "Vos données restent les vôtres.",

    // Home — FAQ
    "home.faq.eyebrow": "Questions fréquentes",
    "home.faq.title": "Ce qu'on nous demande le plus.",

    // Home — CTA finale
    "home.finalCta.title": "Prêt à voir Botler chez vous ?",
    "home.finalCta.subtitle": "Parlez-en à Botler ou réservez un créneau — sans engagement.",

    // Home — Réalisations (§6bis section 5)
    "home.showcase.eyebrow": "Réalisations",
    "home.showcase.title": "Ce qu'on a déjà livré.",
    "home.showcase.description": "Un aperçu de ce qu'on construit pour nos clients, secteur par secteur.",
    "home.sectors.tourism.desc": "Guide virtuel pour vos visiteurs",
    "home.sectors.tourism.stat": "+40% de satisfaction",
    "home.sectors.viticulture.desc": "Sommelier virtuel pour conseils œnologiques",
    "home.sectors.viticulture.stat": "+35% de ventes",
    "home.sectors.restaurants.desc": "Votre meilleur assistant restaurateur 24h/24",
    "home.sectors.restaurants.stat": "+50% de réservations",
    "home.sectors.bakery.desc": "Le vendeur en boulangerie que vous rêvez",
    "home.sectors.bakery.stat": "+30% de commandes",
    "home.sectors.realEstate.desc": "Votre agent virtuel pour mieux qualifier vos futurs clients",
    "home.sectors.realEstate.stat": "+45% de contacts",
    "home.sectors.accommodation.desc": "Concierge virtuel pour vos clients",
    "home.sectors.accommodation.stat": "+35% de réservations",

    // CTA Section
    "cta.title1": "Rejoignez les entreprises qui ont déjà",
    "cta.highlight": "révolutionné",
    "cta.title2": "leur relation client avec Botler™.",
    "cta.description": "Déployez votre chatbot en moins de 5 minutes et commencez à améliorer votre relation client dès aujourd'hui.",
    "cta.button": "Récupérez mon chatbot",

    // Footer
    "footer.description": "Des sites, des apps et des agents IA conçus et livrés par Botler360.",
    "footer.company": "Entreprise",
    "footer.location": "France & Royaume-Uni",
    "footer.legal": "Mentions légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.cookies": "Politique de cookies",
    "footer.rights": "Tous droits réservés.",
    "footer.tagline": "Conçu par une équipe humaine, propulsé par l'IA.",
    "footer.trust.humanTeam": "Derrière nos outils IA, il y a une équipe humaine.",
    "footer.trust.support": "On vous accompagne à chaque étape.",
    "footer.trust.location": "Équipe basée en France & Royaume-Uni",
    "footer.trust.ethical": "IA éthique et transparente",
    "footer.trust.ownership": "Vous gardez 100% la propriété de vos outils.",
    "footer.trust.smile": "Botler360, c'est la technologie avec le sourire.",
    
    // Demo Page
    "demo.title1": "Découvrez Botler™",
    "demo.highlight": "en action",
    "demo.description": "Explorez nos démonstrations vidéo pour chaque secteur d'activité et découvrez comment Botler™ peut transformer votre relation client.",
    "demo.selectSector": "Sélectionnez un secteur",
    "demo.watchVideo": "Regarder la vidéo",
    "demo.features": "Fonctionnalités clés",
    "demo.noVideo": "Vidéo bientôt disponible",
    "demo.tourism.name": "Tourisme",
    "demo.tourism.description": "Découvrez comment Botler™ guide vos visiteurs et répond à toutes leurs questions sur votre destination.",
    "demo.tourism.feature1": "Recommandations personnalisées",
    "demo.tourism.feature2": "Support multilingue",
    "demo.tourism.feature3": "Disponible 24h/24",
    "demo.viticulture.name": "Viticulture",
    "demo.viticulture.description": "Votre sommelier virtuel conseille vos clients sur les accords mets-vins et vos cuvées.",
    "demo.viticulture.feature1": "Conseils œnologiques",
    "demo.viticulture.feature2": "Réservation de visites",
    "demo.viticulture.feature3": "Présentation des cuvées",
    "demo.restaurants.name": "Restaurants",
    "demo.restaurants.description": "Botler™ gère vos réservations et présente votre carte à vos clients gourmets.",
    "demo.restaurants.feature1": "Gestion des réservations",
    "demo.restaurants.feature2": "Présentation du menu",
    "demo.restaurants.feature3": "Informations allergènes",
    "demo.bakery.name": "Boulangerie",
    "demo.bakery.description": "Le vendeur virtuel idéal pour présenter vos produits et prendre les commandes.",
    "demo.bakery.feature1": "Catalogue produits",
    "demo.bakery.feature2": "Prise de commandes",
    "demo.bakery.feature3": "Horaires et disponibilités",
    "demo.realEstate.name": "Immobilier",
    "demo.realEstate.description": "Qualifiez automatiquement vos prospects et présentez vos biens immobiliers.",
    "demo.realEstate.feature1": "Qualification prospects",
    "demo.realEstate.feature2": "Présentation des biens",
    "demo.realEstate.feature3": "Prise de rendez-vous",
    "demo.accommodation.name": "Hébergements",
    "demo.accommodation.description": "Votre concierge virtuel répond aux questions de vos clients voyageurs.",
    "demo.accommodation.feature1": "Informations séjour",
    "demo.accommodation.feature2": "Services disponibles",
    "demo.accommodation.feature3": "Recommandations locales",
    "demo.boutiques.name": "Boutiques & Commerces",
    "demo.boutiques.description": "Découvrez comment Botler™ accompagne vos clients en boutique et booste vos ventes.",
    "demo.boutiques.feature1": "Catalogue produits interactif",
    "demo.boutiques.feature2": "Click & collect automatisé",
    "demo.boutiques.feature3": "Programme fidélité intégré",
    "demo.websites.name": "Sites Web Professionnels",
    "demo.websites.description": "Explorez nos sites web clé en main avec chatbot intégré pour convertir vos visiteurs.",
    "demo.websites.feature1": "Design moderne et responsive",
    "demo.websites.feature2": "Chatbot intégré offert",
    "demo.websites.feature3": "Optimisation SEO incluse",
    "demo.stats.clients": "Clients satisfaits",
    "demo.stats.hours": "Service client économisé",
    "demo.stats.satisfaction": "Satisfaction client",
    
    // Solutions Page
    "solutions.title1": "Nos",
    "solutions.highlight": "Solutions Digitales",
    "solutions.description": "Développez votre présence en ligne avec nos solutions sur mesure, conçues pour booster votre activité.",
    "solutions.pricing.title1": "Tarifs",
    "solutions.pricing.highlight": "Chatbot",
    "solutions.pricing.subtitle": "Tarifs transparents et adaptés à vos besoins",
    "solutions.pricing.perMonth": "/mois",
    "solutions.pricing.recommended": "Recommandé",
    "solutions.pricing.commission": "1% de commission sur chaque vente effectuée entièrement avec Botler (Packs Expert et Expert PME)",
    
    // Pack Junior
    "solutions.pricing.junior.desc": "Pour tous types d'entreprises",
    "solutions.pricing.junior.f1": "Installation rapide",
    "solutions.pricing.junior.f2": "Personnalisé à votre charte graphique",
    "solutions.pricing.junior.f3": "Réponses sur-mesure aux questions visiteurs",
    "solutions.pricing.junior.f4": "Multi-langues",
    "solutions.pricing.junior.cta": "Commencer",
    
    // Pack Expert
    "solutions.pricing.expert.desc": "Parfait pour indépendants et micro-équipes",
    "solutions.pricing.expert.f1": "Matching intelligent sur base de données ciblée",
    "solutions.pricing.expert.f2": "Installation simple et rapide",
    "solutions.pricing.expert.f3": "Personnalisé à votre charte graphique",
    "solutions.pricing.expert.f4": "Assistant commercial intégré (prospects, alertes email, prise de RDV)",
    "solutions.pricing.expert.f5": "Multilingue",
    "solutions.pricing.expert.f6": "Solution clé en main pour générer vos premiers leads",
    "solutions.pricing.expert.cta": "Choisir Expert",
    
    // Pack Expert PME
    "solutions.pricing.expertPME.desc": "Conçu pour les PME en croissance",
    "solutions.pricing.expertPME.f1": "Pensé pour les petites et moyennes entreprises",
    "solutions.pricing.expertPME.f2": "Filtrage intelligent + matching avancé",
    "solutions.pricing.expertPME.f3": "Optimisé pour un contenu volumineux",
    "solutions.pricing.expertPME.f4": "Personnalisé à votre image et multilingue",
    "solutions.pricing.expertPME.f5": "Assistant commercial avec alertes et création auto de prospects",
    "solutions.pricing.expertPME.f6": "Bot robuste pour gérer un volume important de demandes",
    "solutions.pricing.expertPME.cta": "Choisir Expert PME",
    
    // Pack Custom
    "solutions.pricing.custom.name": "Demande ou besoin spécifique ?",
    "solutions.pricing.custom.price": "Sur devis",
    "solutions.pricing.custom.desc": "Solution personnalisée selon vos besoins spécifiques",
    "solutions.pricing.custom.f1": "Accompagnement sur-mesure",
    "solutions.pricing.custom.f2": "Fonctionnalités avancées à la carte",
    "solutions.pricing.custom.cta": "Nous contacter",
    "solutions.guarantees.satisfaction.title": "Satisfaction garantie",
    "solutions.guarantees.satisfaction.desc": "30 jours d'essai gratuit",
    "solutions.guarantees.deploy.title": "Déploiement rapide",
    "solutions.guarantees.deploy.desc": "En ligne en 24h maximum",
    "solutions.guarantees.support.title": "Support expert",
    "solutions.guarantees.support.desc": "Équipe dédiée à votre succès",
    "solutions.website.badge": "Offre Spéciale",
    "solutions.website.title": "Site Web Vitrine Professionnel",
    "solutions.website.description": "Une solution complète pour créer votre présence en ligne professionnelle rapidement et efficacement.",
    "solutions.website.h1": "Livraison en 24h",
    "solutions.website.h2": "Design responsive",
    "solutions.website.h3": "Hébergement inclus",
    "solutions.website.h4": "Compatible mobile",
    "solutions.website.f1": "Design moderne et responsive",
    "solutions.website.f2": "Hébergement web sécurisé",
    "solutions.website.f3": "Certificat SSL gratuit",
    "solutions.website.f4": "Optimisation SEO de base",
    "solutions.website.f5": "Formulaire de contact",
    "solutions.website.f6": "Intégration réseaux sociaux",
    "solutions.website.f7": "Support technique 30 jours",
    "solutions.website.f8": "Formation à l'utilisation",
    "solutions.website.f9": "Sauvegarde automatique",
    "solutions.website.f10": "Statistiques de visite",
    "solutions.website.included": "Ce qui est inclus",
    "solutions.website.cta": "Commander maintenant",
    "solutions.additional.title1": "Autres",
    "solutions.additional.highlight": "Solutions",
    "solutions.additional.description": "Complétez votre présence digitale avec nos services additionnels",
    "solutions.additional.mobile.title": "Application Mobile",
    "solutions.additional.mobile.desc": "App iOS et Android sur mesure pour votre entreprise",
    "solutions.additional.video360.title": "Vidéos 360° immersives",
    "solutions.additional.video360.desc": "Visites virtuelles pour hôtels, restaurants, musées - une expérience immersive",
    "solutions.additional.video360.price": "À partir de 125€",
    "solutions.additional.audio.title": "Musiques & podcasts",
    "solutions.additional.audio.desc": "Identité sonore sur-mesure : musiques d'ambiance, annonces, podcasts brandés",
    "solutions.additional.audio.price": "À partir de 5€",
    "solutions.additional.custom.title": "Projets sur-mesure",
    "solutions.additional.custom.desc": "Dashboards, automatisations, outils métier : on concrétise votre idée avec l'IA.",
    "solutions.additional.custom.price": "Sur devis",

    // Websites Page
    "websites.badge": "Site Web Professionnel",
    "websites.title1": "Votre site web professionnel.",
    "websites.highlight": "Clé en main.",
    "websites.title2": "249€ tout compris... à vie.",
    "websites.description": "Un site web moderne, optimisé SEO et mobile, créé avec l'IA et livré en 24-48h.",
    "websites.priceLabel": "tout inclus, paiement unique",
    "websites.highlight1": "Livraison 24-48h",
    "websites.highlight2": "Design responsive",
    "websites.highlight3": "Hébergement inclus",
    "websites.highlight4": "Compatible mobile",
    "websites.cta": "Commander mon site",
    "websites.bonus.title": "Bonus : Chatbot intégré offert le premier mois !",
    "websites.bonus.description": "Chaque site web inclut un chatbot Botler™ gratuit pendant 30 jours pour booster vos conversions.",
    "websites.points.title1": "Pourquoi choisir",
    "websites.points.highlight": "Botler360 ?",
    "websites.point1.title": "Ne vous cachez plus",
    "websites.point1.desc": "Ayez enfin une présence en ligne professionnelle qui vous représente.",
    "websites.point2.title": "Soyez visible",
    "websites.point2.desc": "Site optimisé SEO pour être trouvé sur Google par vos futurs clients.",
    "websites.point3.title": "Créez des opportunités",
    "websites.point3.desc": "Transformez les visiteurs en clients avec un site qui convertit.",
    "websites.point4.title": "Zéro effort",
    "websites.point4.desc": "On s'occupe de tout : design, développement, hébergement, maintenance.",
    "websites.features.title": "Tout ce qui est inclus",
    "websites.feature1": "Design moderne et responsive",
    "websites.feature2": "Hébergement web sécurisé",
    "websites.feature3": "Certificat SSL gratuit (HTTPS)",
    "websites.feature4": "Optimisation SEO de base",
    "websites.feature5": "Formulaire de contact",
    "websites.feature6": "Intégration réseaux sociaux",
    "websites.feature7": "Support technique 30 jours",
    "websites.feature8": "Formation à l'utilisation",
    "websites.feature9": "Sauvegarde automatique",
    "websites.feature10": "Statistiques de visite",
    "websites.compare.title1": "Comparez et",
    "websites.compare.highlight": "économisez",
    "websites.compare.price": "Prix",
    "websites.compare.delivery": "Délai",
    "websites.compare.hosting": "Hébergement inclus",
    "websites.compare.seo": "Optimisation SEO",
    "websites.compare.support": "Support",
    "websites.compare.chatbot": "Chatbot intégré",
    "websites.compare.diy": "DIY",
    "websites.compare.free1month": "1 mois offert",
    "websites.cta.title1": "Prêt à lancer",
    "websites.cta.highlight": "votre site ?",
    "websites.cta.description": "Commandez maintenant et recevez votre site professionnel en 24-48h.",
    "websites.cta.button": "Commander maintenant",

    // Mobile Apps Page
    "mobileapps.badge": "Application Mobile",
    "mobileapps.title1": "Votre application mobile,",
    "mobileapps.highlight": "prête en 7 jours.",
    "mobileapps.title2": "Pour seulement 249€.",
    "mobileapps.description": "Une app iOS & Android personnalisée pour gérer votre business et fidéliser vos clients.",
    "mobileapps.priceLabel": "tout inclus",
    "mobileapps.highlight1": "iOS & Android",
    "mobileapps.highlight2": "Livraison 7 jours",
    "mobileapps.highlight3": "Publication stores",
    "mobileapps.highlight4": "Design personnalisé",
    "mobileapps.cta": "Commander mon app",
    "mobileapps.points.title1": "Pourquoi une",
    "mobileapps.points.highlight": "app mobile ?",
    "mobileapps.point1.title": "L'app la moins chère",
    "mobileapps.point1.desc": "249€ au lieu de 5000€+ en agence traditionnelle.",
    "mobileapps.point2.title": "Livraison express",
    "mobileapps.point2.desc": "Votre app prête en 7 jours, pas en plusieurs mois.",
    "mobileapps.point3.title": "Transparence totale",
    "mobileapps.point3.desc": "Prix fixe, pas de surprises ni de frais cachés.",
    "mobileapps.point4.title": "Zéro risque",
    "mobileapps.point4.desc": "Satisfait ou remboursé pendant 30 jours.",
    "mobileapps.features.title": "13 fonctionnalités incluses",
    "mobileapps.feature1": "Design personnalisé à votre image",
    "mobileapps.feature2": "Compatible iOS et Android",
    "mobileapps.feature3": "Notifications push",
    "mobileapps.feature4": "Catalogue produits/services",
    "mobileapps.feature5": "Système de réservation",
    "mobileapps.feature6": "Programme de fidélité",
    "mobileapps.feature7": "Paiement en ligne intégré",
    "mobileapps.feature8": "Messagerie intégrée",
    "mobileapps.feature9": "Géolocalisation",
    "mobileapps.feature10": "Mode hors-ligne",
    "mobileapps.feature11": "Statistiques d'utilisation",
    "mobileapps.feature12": "Mises à jour gratuites 1 an",
    "mobileapps.feature13": "Support technique dédié",
    "mobileapps.process.title1": "Un processus",
    "mobileapps.process.highlight": "simple en 3 étapes",
    "mobileapps.process.step1.title": "1. Briefing",
    "mobileapps.process.step1.desc": "Vous nous décrivez vos besoins et votre identité visuelle.",
    "mobileapps.process.step2.title": "2. Développement",
    "mobileapps.process.step2.desc": "Notre équipe crée votre app avec l'IA en 5-7 jours.",
    "mobileapps.process.step3.title": "3. Livraison",
    "mobileapps.process.step3.desc": "Publication sur App Store et Google Play incluse.",
    "mobileapps.faq.title": "Questions fréquentes",
    "mobileapps.faq.q1": "L'app est-elle vraiment à moi ?",
    "mobileapps.faq.a1": "Oui, vous êtes 100% propriétaire de votre application.",
    "mobileapps.faq.q2": "Quels sont les frais récurrents ?",
    "mobileapps.faq.a2": "Aucun frais caché. Seuls les frais des stores (Apple 99€/an, Google 25€ une fois) s'appliquent.",
    "mobileapps.faq.q3": "Puis-je modifier l'app après livraison ?",
    "mobileapps.faq.a3": "Oui, les mises à jour de contenu sont gratuites pendant 1 an.",
    "mobileapps.faq.q4": "Comment se passe le support ?",
    "mobileapps.faq.a4": "Vous bénéficiez d'un support technique dédié par email pendant 1 an.",
    "mobileapps.cta.title1": "Prêt à lancer",
    "mobileapps.cta.highlight": "votre app ?",
    "mobileapps.cta.description": "Commandez maintenant et recevez votre application en 7 jours.",
    "mobileapps.cta.button": "Commander maintenant",

    // Contact Page
    "contact.title1": "Contactez",
    "contact.highlight": "notre équipe",
    "contact.description": "Discutons de votre projet et découvrez comment Botler™ peut transformer votre relation client.",
    "contact.form.title": "Envoyez-nous un message",
    "contact.form.name": "Nom complet",
    "contact.form.namePlaceholder": "Votre nom",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "votre@email.com",
    "contact.form.company": "Entreprise",
    "contact.form.companyPlaceholder": "Nom de votre entreprise",
    "contact.form.sector": "Secteur d'activité",
    "contact.form.sectorPlaceholder": "Sélectionnez un secteur",
    "contact.form.other": "Autre",
    "contact.form.projectType": "Type de projet",
    "contact.form.projectTypePlaceholder": "Sélectionnez un type de projet",
    "contact.form.projectType.chatbot": "Chatbot",
    "contact.form.projectType.website": "Site web",
    "contact.form.projectType.websiteChatbot": "Site web + Chatbot",
    "contact.form.projectType.mobileApp": "Application Mobile",
    "contact.form.projectType.video360": "Vidéo 360°",
    "contact.form.projectType.musicPodcast": "Musique / Podcast",
    "contact.form.projectType.custom": "Projet sur-mesure",
    "contact.form.phone": "Téléphone",
    "contact.form.phonePlaceholder": "+33 6 00 00 00 00",
    "contact.form.attachment": "Joindre un dossier",
    "contact.form.attachmentPlaceholder": "Télécharger un fichier (PDF, DOC, image)",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Décrivez votre projet...",
    "contact.form.submit": "Envoyer le message",
    "contact.form.sending": "Envoi en cours...",
    "contact.form.success": "Message envoyé avec succès ! Nous vous répondrons sous 24h.",
    "contact.info.title": "Nos coordonnées",
    "contact.info.phone": "Téléphone",
    "contact.info.email": "Email",
    "contact.info.location": "Localisation",
    "contact.benefits.title": "Pourquoi nous contacter ?",
    "contact.benefits.fast.title": "Réponse rapide",
    "contact.benefits.fast.desc": "Notre équipe vous répond sous 24h",
    "contact.benefits.personal.title": "Accompagnement personnalisé",
    "contact.benefits.personal.desc": "Un expert dédié à votre projet",
    "contact.benefits.free.title": "Devis gratuit",
    "contact.benefits.free.desc": "Sans engagement de votre part",
    "contact.mascot": "Notre équipe est là pour vous accompagner dans votre transformation digitale.",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.solutions": "Our Solutions",
    "nav.demo": "Demo",
    "nav.contact": "Contact",
    "nav.sectors": "Sectors",
    "nav.getStarted": "Get Started",
    "nav.hub.offer": "What we do",
    "nav.hub.showcase": "Showcase",
    "nav.hub.talk": "Talk to Botler",
    "nav.hub.book": "Book a call",

    // Sectors
    "sector.tourism": "Tourism",
    "sector.viticulture": "Viticulture",
    "sector.restaurants": "Restaurants",
    "sector.bakery": "Bakery",
    "sector.realEstate": "Real Estate",
    "sector.accommodation": "Accommodation",

    // Sector Pages - Tourism
    "sector.tourisme.badge": "Tourism Solution",
    "sector.tourisme.title1": "Botler™ for",
    "sector.tourisme.highlight": "Tourism",
    "sector.tourisme.description": "Transform your visitors' experience with a virtual assistant available 24/7, capable of answering all their questions about your destination.",
    "sector.tourisme.challenge1": "Visitors leaving without answers to their questions",
    "sector.tourisme.challenge2": "Overwhelmed team during peak season",
    "sector.tourisme.challenge3": "Difficulty communicating in multiple languages",
    "sector.tourisme.challenges.title1": "Challenges in the",
    "sector.tourisme.challenges.highlight": "tourism sector",
    "sector.tourisme.challenges.description": "Tourism faces unique availability and multilingual challenges.",
    "sector.tourisme.solutions.title1": "Our",
    "sector.tourisme.solutions.highlight": "solutions",
    "sector.tourisme.solution1.title": "Multilingual assistant",
    "sector.tourisme.solution1.desc": "Respond to your visitors in their language, automatically.",
    "sector.tourisme.solution2.title": "Available 24/7",
    "sector.tourisme.solution2.desc": "Never lose visitors, even outside opening hours.",
    "sector.tourisme.solution3.title": "Personalized recommendations",
    "sector.tourisme.solution3.desc": "Suggest the best activities based on each person's preferences.",
    "sector.tourisme.stat1.value": "+40%",
    "sector.tourisme.stat1.label": "Visitor satisfaction",
    "sector.tourisme.stat2.value": "15h",
    "sector.tourisme.stat2.label": "Saved per week",
    "sector.tourisme.stat3.value": "24/7",
    "sector.tourisme.stat3.label": "Availability",
    "sector.tourisme.video.title": "See Botler™ in action",
    "sector.tourisme.testimonial.text": "Botler™ has revolutionized our visitor reception. +40% satisfaction and 24/7 availability that makes the difference.",
    "sector.tourisme.testimonial.author": "Bordeaux Tourism Office",
    "sector.tourisme.testimonial.role": "Director",

    // Sector Pages - Viticulture
    "sector.viticulture.badge": "Viticulture Solution",
    "sector.viticulture.title1": "Botler™ for",
    "sector.viticulture.highlight": "Viticulture",
    "sector.viticulture.description": "Your virtual sommelier advises your visitors on food-wine pairings and presents your vintages with passion.",
    "sector.viticulture.challenge1": "Customers hesitating without personalized advice",
    "sector.viticulture.challenge2": "Lack of time to welcome each visitor",
    "sector.viticulture.challenge3": "Lost sales outside opening hours",
    "sector.viticulture.challenges.title1": "Challenges in",
    "sector.viticulture.challenges.highlight": "viticulture",
    "sector.viticulture.challenges.description": "The wine world requires expertise and availability to advise customers.",
    "sector.viticulture.solutions.title1": "Our",
    "sector.viticulture.solutions.highlight": "solutions",
    "sector.viticulture.solution1.title": "Virtual sommelier",
    "sector.viticulture.solution1.desc": "Personalized wine advice for each visitor.",
    "sector.viticulture.solution2.title": "Visit booking",
    "sector.viticulture.solution2.desc": "Automatically manage tasting requests.",
    "sector.viticulture.solution3.title": "Vintage presentation",
    "sector.viticulture.solution3.desc": "Showcase your production with passion.",
    "sector.viticulture.stat1.value": "+35%",
    "sector.viticulture.stat1.label": "Online sales",
    "sector.viticulture.stat2.value": "+50%",
    "sector.viticulture.stat2.label": "Visit bookings",
    "sector.viticulture.stat3.value": "8",
    "sector.viticulture.stat3.label": "Languages supported",
    "sector.viticulture.video.title": "Discover our virtual sommelier",
    "sector.viticulture.testimonial.text": "Our online sales increased by 35% thanks to Botler™'s personalized advice.",
    "sector.viticulture.testimonial.author": "Domaine des Vignes",
    "sector.viticulture.testimonial.role": "Owner",

    // Sector Pages - Restaurants
    "sector.restaurants.badge": "Restaurant Solution",
    "sector.restaurants.title1": "Botler™ for",
    "sector.restaurants.highlight": "Restaurants",
    "sector.restaurants.description": "Your best restaurant assistant 24/7 to manage reservations and present your menu.",
    "sector.restaurants.challenge1": "Missed calls = lost reservations",
    "sector.restaurants.challenge2": "Repetitive questions about the menu and allergens",
    "sector.restaurants.challenge3": "Managing the rush during service",
    "sector.restaurants.challenges.title1": "Challenges in",
    "sector.restaurants.challenges.highlight": "restaurants",
    "sector.restaurants.challenges.description": "Restaurants require responsiveness and organization to satisfy each customer.",
    "sector.restaurants.solutions.title1": "Our",
    "sector.restaurants.solutions.highlight": "solutions",
    "sector.restaurants.solution1.title": "Reservation management",
    "sector.restaurants.solution1.desc": "Accept reservations 24/7, even during service.",
    "sector.restaurants.solution2.title": "Menu presentation",
    "sector.restaurants.solution2.desc": "Answer questions about dishes and allergens.",
    "sector.restaurants.solution3.title": "Takeaway orders",
    "sector.restaurants.solution3.desc": "Facilitate click & collect orders.",
    "sector.restaurants.stat1.value": "+50%",
    "sector.restaurants.stat1.label": "Reservations",
    "sector.restaurants.stat2.value": "0",
    "sector.restaurants.stat2.label": "Missed calls",
    "sector.restaurants.stat3.value": "5min",
    "sector.restaurants.stat3.label": "Average response time",
    "sector.restaurants.video.title": "Botler™ in restaurants",
    "sector.restaurants.testimonial.text": "Our reservations increased by 50% thanks to Botler™'s permanent availability.",
    "sector.restaurants.testimonial.author": "Restaurant Le Gourmet",
    "sector.restaurants.testimonial.role": "Chef owner",

    // Sector Pages - Bakery
    "sector.boulangerie.badge": "Bakery Solution",
    "sector.boulangerie.title1": "Botler™ for",
    "sector.boulangerie.highlight": "Bakeries",
    "sector.boulangerie.description": "The ideal virtual salesperson to present your products and take orders.",
    "sector.boulangerie.challenge1": "Queue that discourages customers",
    "sector.boulangerie.challenge2": "Special orders difficult to manage",
    "sector.boulangerie.challenge3": "Unsold products at end of day",
    "sector.boulangerie.challenges.title1": "Challenges in",
    "sector.boulangerie.challenges.highlight": "bakeries",
    "sector.boulangerie.challenges.description": "Artisan bakeries must combine quality and efficiency.",
    "sector.boulangerie.solutions.title1": "Our",
    "sector.boulangerie.solutions.highlight": "solutions",
    "sector.boulangerie.solution1.title": "Product catalog",
    "sector.boulangerie.solution1.desc": "Present all your breads and pastries.",
    "sector.boulangerie.solution2.title": "Order taking",
    "sector.boulangerie.solution2.desc": "Online orders for in-store pickup.",
    "sector.boulangerie.solution3.title": "Hours and availability",
    "sector.boulangerie.solution3.desc": "Inform about available products in real time.",
    "sector.boulangerie.stat1.value": "+30%",
    "sector.boulangerie.stat1.label": "Online orders",
    "sector.boulangerie.stat2.value": "-20%",
    "sector.boulangerie.stat2.label": "Unsold items",
    "sector.boulangerie.stat3.value": "100%",
    "sector.boulangerie.stat3.label": "Satisfied customers",
    "sector.boulangerie.video.title": "Botler™ in bakeries",
    "sector.boulangerie.testimonial.text": "Online orders increased by 30% and our unsold items decreased by 20%.",
    "sector.boulangerie.testimonial.author": "Corner Bakery",
    "sector.boulangerie.testimonial.role": "Artisan baker",

    // Sector Pages - Real Estate
    "sector.immobilier.badge": "Real Estate Solution",
    "sector.immobilier.title1": "Botler™ for",
    "sector.immobilier.highlight": "Real Estate",
    "sector.immobilier.description": "Your virtual agent to qualify your prospects and present your properties 24/7.",
    "sector.immobilier.challenge1": "Unqualified prospects wasting time",
    "sector.immobilier.challenge2": "Information requests outside office hours",
    "sector.immobilier.challenge3": "Useless visits for unsuitable properties",
    "sector.immobilier.challenges.title1": "Challenges in",
    "sector.immobilier.challenges.highlight": "real estate",
    "sector.immobilier.challenges.description": "Real estate requires responsiveness and precise prospect qualification.",
    "sector.immobilier.solutions.title1": "Our",
    "sector.immobilier.solutions.highlight": "solutions",
    "sector.immobilier.solution1.title": "Prospect qualification",
    "sector.immobilier.solution1.desc": "Identify serious buyers automatically.",
    "sector.immobilier.solution2.title": "Property presentation",
    "sector.immobilier.solution2.desc": "Answer questions about each property.",
    "sector.immobilier.solution3.title": "Appointment booking",
    "sector.immobilier.solution3.desc": "Schedule visits directly in your calendar.",
    "sector.immobilier.stat1.value": "+45%",
    "sector.immobilier.stat1.label": "Qualified contacts",
    "sector.immobilier.stat2.value": "2x",
    "sector.immobilier.stat2.label": "More useful visits",
    "sector.immobilier.stat3.value": "24/7",
    "sector.immobilier.stat3.label": "Availability",
    "sector.immobilier.video.title": "Botler™ in real estate",
    "sector.immobilier.testimonial.text": "Our qualified contacts increased by 45% and our visits are much more effective.",
    "sector.immobilier.testimonial.author": "Immo Plus Agency",
    "sector.immobilier.testimonial.role": "Agency director",

    // Sector Pages - Accommodation
    "sector.hebergements.badge": "Accommodation Solution",
    "sector.hebergements.title1": "Botler™ for",
    "sector.hebergements.highlight": "Accommodation",
    "sector.hebergements.description": "Your virtual concierge to assist your traveling guests before, during and after their stay.",
    "sector.hebergements.challenge1": "Repetitive guest questions (WiFi, check-in...)",
    "sector.hebergements.challenge2": "Requests outside reception hours",
    "sector.hebergements.challenge3": "Difficulty personalizing the guest experience",
    "sector.hebergements.challenges.title1": "Challenges in",
    "sector.hebergements.challenges.highlight": "accommodation",
    "sector.hebergements.challenges.description": "Accommodation requires availability and personalization for each traveler.",
    "sector.hebergements.solutions.title1": "Our",
    "sector.hebergements.solutions.highlight": "solutions",
    "sector.hebergements.solution1.title": "Stay information",
    "sector.hebergements.solution1.desc": "Answer questions about WiFi, parking, check-in...",
    "sector.hebergements.solution2.title": "Available services",
    "sector.hebergements.solution2.desc": "Present breakfast, spa, room service...",
    "sector.hebergements.solution3.title": "Local recommendations",
    "sector.hebergements.solution3.desc": "Suggest restaurants, activities and sites to visit.",
    "sector.hebergements.stat1.value": "+35%",
    "sector.hebergements.stat1.label": "Direct bookings",
    "sector.hebergements.stat2.value": "+40%",
    "sector.hebergements.stat2.label": "Guest satisfaction",
    "sector.hebergements.stat3.value": "90%",
    "sector.hebergements.stat3.label": "Questions resolved",
    "sector.hebergements.video.title": "Botler™ for accommodation",
    "sector.hebergements.testimonial.text": "Botler™ has revolutionized our reception. +40% satisfaction and 24/7 availability.",
    "sector.hebergements.testimonial.author": "Hotel du Phare",
    "sector.hebergements.testimonial.role": "Director",

    // Home — Hero (relift 2026-08)
    "home.hero.cta1": "Watch demos",
    "home.hero.cta2": "Get my chatbot",
    "home.hero.h1Pre": "We build your sites, your apps, and the",
    "home.hero.h1Highlight": "AI agents",
    "home.hero.h1Post": "that talk to your customers.",
    "home.hero.subtitle": "Sites, online shops, apps and AI agents — built with AI, delivered in days.",
    "home.hero.manifesto": "We show what we can do. We don't just say it.",

    // Home — Shared CTA labels (two-state offer cards, hero, final CTA)
    "home.cta.talkToBotler": "Talk to Botler",
    "home.cta.bookMeeting": "Book a call",
    "home.cta.viewPage": "View the page",

    // Home — Botler live (embedded hero agent)
    "home.botlerLive.eyebrow": "Botler live",
    "home.botlerLive.title": "Talk to it, right now.",
    "home.botlerLive.description": "Botler answers live about our sites, apps and AI agents. Type, or turn on the mic to talk out loud.",

    // Home — What we know how to do (4 families, §6)
    "home.offer.eyebrow": "What we know how to do",
    "home.offer.title": "Four ways to save you time.",
    "home.offer.familyA.title": "Sites & online commerce",
    "home.offer.familyA.benefit": "A site with its own built-in AI agent, ready to sell.",
    "home.offer.familyB.title": "Cross-channel AI agents",
    "home.offer.familyB.benefit": "One agent, everywhere your customers look for you.",
    "home.offer.familyC.title": "Apps & platforms",
    "home.offer.familyC.benefit": "Custom apps, client portals and dashboards.",
    "home.offer.familyD.title": "AI studios & formats",
    "home.offer.familyD.benefit": "AI formats designed and produced end to end.",
    "home.offer.aio.text": "Botler also works on your visibility in AI answers (Google AI Overview, Perplexity, ChatGPT, Claude).",

    // Home — How we work
    "home.howWeWork.eyebrow": "How we work",
    "home.howWeWork.title": "Three steps, nothing more.",
    "home.howWeWork.step1.title": "We scope",
    "home.howWeWork.step1.desc": "A conversation with Botler or the team to pin down what you actually need.",
    "home.howWeWork.step2.title": "We build",
    "home.howWeWork.step2.desc": "Site, app or agent, built with AI and checked by the team.",
    "home.howWeWork.step3.title": "We deliver",
    "home.howWeWork.step3.desc": "In days, not months.",

    // Home — What our agents never do
    "home.boundaries.eyebrow": "What our agents never do",
    "home.boundaries.title": "Honesty first.",
    "home.boundaries.item1.title": "Never invents",
    "home.boundaries.item1.desc": "Our agents never make up a feature, a price or an availability.",
    "home.boundaries.item2.title": "No false promises",
    "home.boundaries.item2.desc": "We describe what the tool does, never a guaranteed business outcome.",
    "home.boundaries.item3.title": "Hands off to a human",
    "home.boundaries.item3.desc": "The moment it's beyond scope, the agent hands over to the team.",

    // Home — Booking
    "home.booking.eyebrow": "Book a call",
    "home.booking.title": "Reserve a slot.",
    "home.booking.description": "Pick a time that works for you, we'll take the time to understand your project.",
    "home.booking.fallback": "Online booking is coming soon. In the meantime, write to us.",

    // Home — Data & security
    "home.dataSecurity.eyebrow": "Data & security",
    "home.dataSecurity.title": "Your data stays yours.",

    // Home — FAQ
    "home.faq.eyebrow": "Frequently asked questions",
    "home.faq.title": "What we get asked the most.",

    // Home — Final CTA
    "home.finalCta.title": "Ready to see Botler at work?",
    "home.finalCta.subtitle": "Talk to Botler or book a call — no commitment.",

    // Home — Showcase (§6bis section 5)
    "home.showcase.eyebrow": "Showcase",
    "home.showcase.title": "What we've already delivered.",
    "home.showcase.description": "A look at what we build for our clients, by industry.",
    "home.sectors.tourism.desc": "Virtual guide for your visitors",
    "home.sectors.tourism.stat": "+40% satisfaction",
    "home.sectors.viticulture.desc": "Virtual sommelier for wine advice",
    "home.sectors.viticulture.stat": "+35% sales",
    "home.sectors.restaurants.desc": "Your best restaurant assistant 24/7",
    "home.sectors.restaurants.stat": "+50% bookings",
    "home.sectors.bakery.desc": "The bakery salesperson you've dreamed of",
    "home.sectors.bakery.stat": "+30% orders",
    "home.sectors.realEstate.desc": "Your virtual agent to better qualify future clients",
    "home.sectors.realEstate.stat": "+45% contacts",
    "home.sectors.accommodation.desc": "Virtual concierge for your guests",
    "home.sectors.accommodation.stat": "+35% bookings",

    // CTA Section
    "cta.title1": "Join the companies that have already",
    "cta.highlight": "revolutionized",
    "cta.title2": "their customer relationships with Botler™.",
    "cta.description": "Deploy your chatbot in less than 5 minutes and start improving your customer relationships today.",
    "cta.button": "Get my chatbot",

    // Footer
    "footer.description": "Sites, apps and AI agents designed and delivered by Botler360.",
    "footer.company": "Company",
    "footer.location": "France & United Kingdom",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy Policy",
    "footer.cookies": "Cookie Policy",
    "footer.rights": "All rights reserved.",
    "footer.tagline": "Designed by a human team, powered by AI.",
    "footer.trust.humanTeam": "Behind our AI tools, there's a human team.",
    "footer.trust.support": "We support you at every step.",
    "footer.trust.location": "Team based in France & UK",
    "footer.trust.ethical": "Ethical and transparent AI",
    "footer.trust.ownership": "You keep 100% ownership of your tools.",
    "footer.trust.smile": "Botler360 is technology with a smile.",
    
    // Demo Page
    "demo.title1": "Discover Botler™",
    "demo.highlight": "in action",
    "demo.description": "Explore our video demonstrations for each industry and discover how Botler™ can transform your customer relationships.",
    "demo.selectSector": "Select a sector",
    "demo.watchVideo": "Watch video",
    "demo.features": "Key features",
    "demo.noVideo": "Video coming soon",
    "demo.tourism.name": "Tourism",
    "demo.tourism.description": "Discover how Botler™ guides your visitors and answers all their questions about your destination.",
    "demo.tourism.feature1": "Personalized recommendations",
    "demo.tourism.feature2": "Multilingual support",
    "demo.tourism.feature3": "Available 24/7",
    "demo.viticulture.name": "Viticulture",
    "demo.viticulture.description": "Your virtual sommelier advises your customers on food-wine pairings and your vintages.",
    "demo.viticulture.feature1": "Wine advice",
    "demo.viticulture.feature2": "Visit booking",
    "demo.viticulture.feature3": "Vintage presentation",
    "demo.restaurants.name": "Restaurants",
    "demo.restaurants.description": "Botler™ manages your reservations and presents your menu to your gourmet customers.",
    "demo.restaurants.feature1": "Reservation management",
    "demo.restaurants.feature2": "Menu presentation",
    "demo.restaurants.feature3": "Allergen information",
    "demo.bakery.name": "Bakery",
    "demo.bakery.description": "The ideal virtual salesperson to present your products and take orders.",
    "demo.bakery.feature1": "Product catalog",
    "demo.bakery.feature2": "Order taking",
    "demo.bakery.feature3": "Hours and availability",
    "demo.realEstate.name": "Real Estate",
    "demo.realEstate.description": "Automatically qualify your prospects and present your properties.",
    "demo.realEstate.feature1": "Prospect qualification",
    "demo.realEstate.feature2": "Property presentation",
    "demo.realEstate.feature3": "Appointment booking",
    "demo.accommodation.name": "Accommodation",
    "demo.accommodation.description": "Your virtual concierge answers your traveling guests' questions.",
    "demo.accommodation.feature1": "Stay information",
    "demo.accommodation.feature2": "Available services",
    "demo.accommodation.feature3": "Local recommendations",
    "demo.boutiques.name": "Shops & Retail",
    "demo.boutiques.description": "Discover how Botler™ assists your in-store customers and boosts your sales.",
    "demo.boutiques.feature1": "Interactive product catalog",
    "demo.boutiques.feature2": "Automated click & collect",
    "demo.boutiques.feature3": "Integrated loyalty program",
    "demo.websites.name": "Professional Websites",
    "demo.websites.description": "Explore our turnkey websites with integrated chatbot to convert your visitors.",
    "demo.websites.feature1": "Modern responsive design",
    "demo.websites.feature2": "Free integrated chatbot",
    "demo.websites.feature3": "SEO optimization included",
    "demo.stats.clients": "Satisfied clients",
    "demo.stats.hours": "Customer service saved",
    "demo.stats.satisfaction": "Customer satisfaction",
    
    // Solutions Page
    "solutions.title1": "Our",
    "solutions.highlight": "Digital Solutions",
    "solutions.description": "Develop your online presence with our custom solutions, designed to boost your business.",
    "solutions.pricing.title1": "Chatbot",
    "solutions.pricing.highlight": "Pricing",
    "solutions.pricing.subtitle": "Transparent pricing tailored to your needs",
    "solutions.pricing.perMonth": "/month",
    "solutions.pricing.recommended": "Recommended",
    "solutions.pricing.commission": "1% commission on each sale made entirely with Botler (Expert and Expert SME packs)",
    
    // Pack Junior
    "solutions.pricing.junior.desc": "For all types of businesses",
    "solutions.pricing.junior.f1": "Quick installation",
    "solutions.pricing.junior.f2": "Customized to your brand identity",
    "solutions.pricing.junior.f3": "Custom responses to visitor questions",
    "solutions.pricing.junior.f4": "Multi-language support",
    "solutions.pricing.junior.cta": "Get Started",
    
    // Pack Expert
    "solutions.pricing.expert.desc": "Perfect for freelancers and micro-teams",
    "solutions.pricing.expert.f1": "Smart matching on targeted database",
    "solutions.pricing.expert.f2": "Simple and quick installation",
    "solutions.pricing.expert.f3": "Customized to your brand identity",
    "solutions.pricing.expert.f4": "Integrated sales assistant (leads, email alerts, appointments)",
    "solutions.pricing.expert.f5": "Multilingual",
    "solutions.pricing.expert.f6": "Turnkey solution to generate your first leads",
    "solutions.pricing.expert.cta": "Choose Expert",
    
    // Pack Expert PME
    "solutions.pricing.expertPME.desc": "Designed for growing SMEs",
    "solutions.pricing.expertPME.f1": "Built for small and medium businesses",
    "solutions.pricing.expertPME.f2": "Smart filtering + advanced matching",
    "solutions.pricing.expertPME.f3": "Optimized for large content volumes",
    "solutions.pricing.expertPME.f4": "Customized to your image and multilingual",
    "solutions.pricing.expertPME.f5": "Sales assistant with alerts and auto lead creation",
    "solutions.pricing.expertPME.f6": "Robust bot to handle high volume of requests",
    "solutions.pricing.expertPME.cta": "Choose Expert SME",
    
    // Pack Custom
    "solutions.pricing.custom.name": "Specific request or need?",
    "solutions.pricing.custom.price": "Quote",
    "solutions.pricing.custom.desc": "Custom solution based on your specific needs",
    "solutions.pricing.custom.f1": "Tailored support",
    "solutions.pricing.custom.f2": "Advanced features à la carte",
    "solutions.pricing.custom.cta": "Contact us",
    "solutions.guarantees.satisfaction.title": "Satisfaction guaranteed",
    "solutions.guarantees.satisfaction.desc": "30-day free trial",
    "solutions.guarantees.deploy.title": "Fast deployment",
    "solutions.guarantees.deploy.desc": "Online within 24 hours",
    "solutions.guarantees.support.title": "Expert support",
    "solutions.guarantees.support.desc": "Team dedicated to your success",
    "solutions.website.badge": "Special Offer",
    "solutions.website.title": "Professional Showcase Website",
    "solutions.website.description": "A complete solution to create your professional online presence quickly and efficiently.",
    "solutions.website.h1": "24h delivery",
    "solutions.website.h2": "Responsive design",
    "solutions.website.h3": "Hosting included",
    "solutions.website.h4": "Mobile compatible",
    "solutions.website.f1": "Modern responsive design",
    "solutions.website.f2": "Secure web hosting",
    "solutions.website.f3": "Free SSL certificate",
    "solutions.website.f4": "Basic SEO optimization",
    "solutions.website.f5": "Contact form",
    "solutions.website.f6": "Social media integration",
    "solutions.website.f7": "30-day technical support",
    "solutions.website.f8": "Usage training",
    "solutions.website.f9": "Automatic backup",
    "solutions.website.f10": "Visit statistics",
    "solutions.website.included": "What's included",
    "solutions.website.cta": "Order now",
    "solutions.additional.title1": "Other",
    "solutions.additional.highlight": "Solutions",
    "solutions.additional.description": "Complete your digital presence with our additional services",
    "solutions.additional.mobile.title": "Mobile Application",
    "solutions.additional.mobile.desc": "Custom iOS and Android app for your business",
    "solutions.additional.video360.title": "360° Immersive Videos",
    "solutions.additional.video360.desc": "Virtual tours for hotels, restaurants, museums - an immersive experience",
    "solutions.additional.video360.price": "Starting at €125",
    "solutions.additional.audio.title": "Music & Podcasts",
    "solutions.additional.audio.desc": "Custom audio identity: ambient music, announcements, branded podcasts",
    "solutions.additional.audio.price": "Starting at €5",
    "solutions.additional.custom.title": "Custom Projects",
    "solutions.additional.custom.desc": "Dashboards, automations, business tools: we bring your AI idea to life.",
    "solutions.additional.custom.price": "Quote",

    // Websites Page
    "websites.badge": "Professional Website",
    "websites.title1": "Your professional website.",
    "websites.highlight": "Turnkey.",
    "websites.title2": "€249 all included... for life.",
    "websites.description": "A modern website, SEO and mobile optimized, AI-created and delivered in 24-48h.",
    "websites.priceLabel": "all included, one-time payment",
    "websites.highlight1": "24-48h delivery",
    "websites.highlight2": "Responsive design",
    "websites.highlight3": "Hosting included",
    "websites.highlight4": "Mobile compatible",
    "websites.cta": "Order my website",
    "websites.bonus.title": "Bonus: Free integrated chatbot for the first month!",
    "websites.bonus.description": "Each website includes a free Botler™ chatbot for 30 days to boost your conversions.",
    "websites.points.title1": "Why choose",
    "websites.points.highlight": "Botler360?",
    "websites.point1.title": "Stop hiding",
    "websites.point1.desc": "Finally have a professional online presence that represents you.",
    "websites.point2.title": "Be visible",
    "websites.point2.desc": "SEO-optimized site to be found on Google by your future customers.",
    "websites.point3.title": "Create opportunities",
    "websites.point3.desc": "Turn visitors into customers with a converting website.",
    "websites.point4.title": "Zero effort",
    "websites.point4.desc": "We handle everything: design, development, hosting, maintenance.",
    "websites.features.title": "Everything included",
    "websites.feature1": "Modern responsive design",
    "websites.feature2": "Secure web hosting",
    "websites.feature3": "Free SSL certificate (HTTPS)",
    "websites.feature4": "Basic SEO optimization",
    "websites.feature5": "Contact form",
    "websites.feature6": "Social media integration",
    "websites.feature7": "30-day technical support",
    "websites.feature8": "Usage training",
    "websites.feature9": "Automatic backup",
    "websites.feature10": "Visit statistics",
    "websites.compare.title1": "Compare and",
    "websites.compare.highlight": "save",
    "websites.compare.price": "Price",
    "websites.compare.delivery": "Delivery",
    "websites.compare.hosting": "Hosting included",
    "websites.compare.seo": "SEO optimization",
    "websites.compare.support": "Support",
    "websites.compare.chatbot": "Integrated chatbot",
    "websites.compare.diy": "DIY",
    "websites.compare.free1month": "1 month free",
    "websites.cta.title1": "Ready to launch",
    "websites.cta.highlight": "your site?",
    "websites.cta.description": "Order now and receive your professional website in 24-48h.",
    "websites.cta.button": "Order now",

    // Mobile Apps Page
    "mobileapps.badge": "Mobile Application",
    "mobileapps.title1": "Your mobile app,",
    "mobileapps.highlight": "ready in 7 days.",
    "mobileapps.title2": "For only €249.",
    "mobileapps.description": "A custom iOS & Android app to manage your business and retain your customers.",
    "mobileapps.priceLabel": "all included",
    "mobileapps.highlight1": "iOS & Android",
    "mobileapps.highlight2": "7-day delivery",
    "mobileapps.highlight3": "Store publication",
    "mobileapps.highlight4": "Custom design",
    "mobileapps.cta": "Order my app",
    "mobileapps.points.title1": "Why a",
    "mobileapps.points.highlight": "mobile app?",
    "mobileapps.point1.title": "The cheapest app",
    "mobileapps.point1.desc": "€249 instead of €5000+ at a traditional agency.",
    "mobileapps.point2.title": "Express delivery",
    "mobileapps.point2.desc": "Your app ready in 7 days, not several months.",
    "mobileapps.point3.title": "Total transparency",
    "mobileapps.point3.desc": "Fixed price, no surprises or hidden fees.",
    "mobileapps.point4.title": "Zero risk",
    "mobileapps.point4.desc": "Satisfied or refunded for 30 days.",
    "mobileapps.features.title": "13 features included",
    "mobileapps.feature1": "Custom design to your image",
    "mobileapps.feature2": "iOS and Android compatible",
    "mobileapps.feature3": "Push notifications",
    "mobileapps.feature4": "Product/service catalog",
    "mobileapps.feature5": "Booking system",
    "mobileapps.feature6": "Loyalty program",
    "mobileapps.feature7": "Integrated online payment",
    "mobileapps.feature8": "Integrated messaging",
    "mobileapps.feature9": "Geolocation",
    "mobileapps.feature10": "Offline mode",
    "mobileapps.feature11": "Usage statistics",
    "mobileapps.feature12": "Free updates 1 year",
    "mobileapps.feature13": "Dedicated technical support",
    "mobileapps.process.title1": "A simple",
    "mobileapps.process.highlight": "3-step process",
    "mobileapps.process.step1.title": "1. Briefing",
    "mobileapps.process.step1.desc": "You describe your needs and visual identity.",
    "mobileapps.process.step2.title": "2. Development",
    "mobileapps.process.step2.desc": "Our team creates your app with AI in 5-7 days.",
    "mobileapps.process.step3.title": "3. Delivery",
    "mobileapps.process.step3.desc": "Publication on App Store and Google Play included.",
    "mobileapps.faq.title": "Frequently asked questions",
    "mobileapps.faq.q1": "Is the app really mine?",
    "mobileapps.faq.a1": "Yes, you are 100% owner of your application.",
    "mobileapps.faq.q2": "What are the recurring fees?",
    "mobileapps.faq.a2": "No hidden fees. Only store fees (Apple €99/year, Google €25 once) apply.",
    "mobileapps.faq.q3": "Can I modify the app after delivery?",
    "mobileapps.faq.a3": "Yes, content updates are free for 1 year.",
    "mobileapps.faq.q4": "How does support work?",
    "mobileapps.faq.a4": "You benefit from dedicated technical support by email for 1 year.",
    "mobileapps.cta.title1": "Ready to launch",
    "mobileapps.cta.highlight": "your app?",
    "mobileapps.cta.description": "Order now and receive your application in 7 days.",
    "mobileapps.cta.button": "Order now",

    // Contact Page
    "contact.title1": "Contact",
    "contact.highlight": "our team",
    "contact.description": "Let's discuss your project and discover how Botler™ can transform your customer relationships.",
    "contact.form.title": "Send us a message",
    "contact.form.name": "Full name",
    "contact.form.namePlaceholder": "Your name",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "your@email.com",
    "contact.form.company": "Company",
    "contact.form.companyPlaceholder": "Your company name",
    "contact.form.sector": "Industry",
    "contact.form.sectorPlaceholder": "Select a sector",
    "contact.form.other": "Other",
    "contact.form.projectType": "Project Type",
    "contact.form.projectTypePlaceholder": "Select a project type",
    "contact.form.projectType.chatbot": "Chatbot",
    "contact.form.projectType.website": "Website",
    "contact.form.projectType.websiteChatbot": "Website + Chatbot",
    "contact.form.projectType.mobileApp": "Mobile Application",
    "contact.form.projectType.video360": "360° Video",
    "contact.form.projectType.musicPodcast": "Music / Podcast",
    "contact.form.projectType.custom": "Custom Project",
    "contact.form.phone": "Phone",
    "contact.form.phonePlaceholder": "+33 6 00 00 00 00",
    "contact.form.attachment": "Attach a file",
    "contact.form.attachmentPlaceholder": "Upload a file (PDF, DOC, image)",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Describe your project...",
    "contact.form.submit": "Send message",
    "contact.form.sending": "Sending...",
    "contact.form.success": "Message sent successfully! We'll respond within 24 hours.",
    "contact.info.title": "Our contact details",
    "contact.info.phone": "Phone",
    "contact.info.email": "Email",
    "contact.info.location": "Location",
    "contact.benefits.title": "Why contact us?",
    "contact.benefits.fast.title": "Quick response",
    "contact.benefits.fast.desc": "Our team responds within 24 hours",
    "contact.benefits.personal.title": "Personalized support",
    "contact.benefits.personal.desc": "An expert dedicated to your project",
    "contact.benefits.free.title": "Free quote",
    "contact.benefits.free.desc": "No commitment required",
    "contact.mascot": "Our team is here to support you in your digital transformation.",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("botler-language");
      if (saved === "en" || saved === "fr") return saved;
    }
    return "fr";
  });

  useEffect(() => {
    localStorage.setItem("botler-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    // Use ?? (not ||) so an intentional empty string ("") is returned as-is
    // instead of falling through to the raw key. Falls back to the key only
    // when the translation is genuinely missing (undefined).
    const value = translations[language][key];
    if (value === undefined) {
      if (typeof console !== "undefined") {
        console.warn(`[i18n] missing key: ${key} (lang=${language})`);
      }
      return key;
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
