import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    "nav.home": "Accueil",
    "nav.solutions": "Nos Solutions",
    "nav.demo": "Démo",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.sectors": "Secteurs",
    "nav.getStarted": "Démarrer maintenant",
    
    // Sectors
    "sector.tourism": "Tourisme",
    "sector.viticulture": "Viticulture",
    "sector.restaurants": "Restaurants",
    "sector.bakery": "Boulangerie",
    "sector.realEstate": "Immobilier",
    "sector.accommodation": "Hébergements",

    // Sector Pages - Tourisme
    "sector.tourisme.badge": "Solution Tourisme",
    "sector.tourisme.title1": "Botler™ pour le",
    "sector.tourisme.highlight": "Tourisme",
    "sector.tourisme.description": "Transformez l'expérience de vos visiteurs avec un assistant virtuel disponible 24h/24, capable de répondre à toutes leurs questions sur votre destination.",
    "sector.tourisme.challenge1": "Visiteurs qui partent sans réponse à leurs questions",
    "sector.tourisme.challenge2": "Équipe débordée pendant les pics de saison",
    "sector.tourisme.challenge3": "Difficulté à communiquer en plusieurs langues",
    "sector.tourisme.challenges.title1": "Les défis du",
    "sector.tourisme.challenges.highlight": "secteur touristique",
    "sector.tourisme.challenges.description": "Le tourisme fait face à des enjeux uniques de disponibilité et de multilinguisme.",
    "sector.tourisme.solutions.title1": "Nos",
    "sector.tourisme.solutions.highlight": "solutions",
    "sector.tourisme.solution1.title": "Assistant multilingue",
    "sector.tourisme.solution1.desc": "Répondez à vos visiteurs dans leur langue, automatiquement.",
    "sector.tourisme.solution2.title": "Disponible 24h/24",
    "sector.tourisme.solution2.desc": "Ne perdez plus de visiteurs, même en dehors des heures d'ouverture.",
    "sector.tourisme.solution3.title": "Recommandations personnalisées",
    "sector.tourisme.solution3.desc": "Suggérez les meilleures activités selon les préférences de chacun.",
    "sector.tourisme.stat1.value": "+40%",
    "sector.tourisme.stat1.label": "Satisfaction visiteurs",
    "sector.tourisme.stat2.value": "15h",
    "sector.tourisme.stat2.label": "Économisées par semaine",
    "sector.tourisme.stat3.value": "24/7",
    "sector.tourisme.stat3.label": "Disponibilité",
    "sector.tourisme.video.title": "Voir Botler™ en action",
    "sector.tourisme.testimonial.text": "Botler™ a révolutionné notre accueil visiteur. +40% de satisfaction et une disponibilité 24h/24 qui fait la différence.",
    "sector.tourisme.testimonial.author": "Office de Tourisme de Bordeaux",
    "sector.tourisme.testimonial.role": "Directeur",

    // Sector Pages - Viticulture
    "sector.viticulture.badge": "Solution Viticulture",
    "sector.viticulture.title1": "Botler™ pour la",
    "sector.viticulture.highlight": "Viticulture",
    "sector.viticulture.description": "Votre sommelier virtuel conseille vos visiteurs sur les accords mets-vins et présente vos cuvées avec passion.",
    "sector.viticulture.challenge1": "Clients qui hésitent sans conseils personnalisés",
    "sector.viticulture.challenge2": "Manque de temps pour accueillir chaque visiteur",
    "sector.viticulture.challenge3": "Ventes perdues en dehors des heures d'ouverture",
    "sector.viticulture.challenges.title1": "Les défis de la",
    "sector.viticulture.challenges.highlight": "viticulture",
    "sector.viticulture.challenges.description": "Le monde du vin nécessite expertise et disponibilité pour conseiller les clients.",
    "sector.viticulture.solutions.title1": "Nos",
    "sector.viticulture.solutions.highlight": "solutions",
    "sector.viticulture.solution1.title": "Sommelier virtuel",
    "sector.viticulture.solution1.desc": "Conseils œnologiques personnalisés pour chaque visiteur.",
    "sector.viticulture.solution2.title": "Réservation de visites",
    "sector.viticulture.solution2.desc": "Gérez automatiquement les demandes de dégustation.",
    "sector.viticulture.solution3.title": "Présentation des cuvées",
    "sector.viticulture.solution3.desc": "Mettez en valeur votre production avec passion.",
    "sector.viticulture.stat1.value": "+35%",
    "sector.viticulture.stat1.label": "Ventes en ligne",
    "sector.viticulture.stat2.value": "+50%",
    "sector.viticulture.stat2.label": "Réservations visites",
    "sector.viticulture.stat3.value": "8",
    "sector.viticulture.stat3.label": "Langues supportées",
    "sector.viticulture.video.title": "Découvrez notre sommelier virtuel",
    "sector.viticulture.testimonial.text": "Nos ventes en ligne ont augmenté de 35% grâce aux conseils personnalisés de Botler™.",
    "sector.viticulture.testimonial.author": "Domaine des Vignes",
    "sector.viticulture.testimonial.role": "Propriétaire",

    // Sector Pages - Restaurants
    "sector.restaurants.badge": "Solution Restaurants",
    "sector.restaurants.title1": "Botler™ pour les",
    "sector.restaurants.highlight": "Restaurants",
    "sector.restaurants.description": "Votre meilleur assistant restaurateur 24h/24 pour gérer les réservations et présenter votre carte.",
    "sector.restaurants.challenge1": "Appels manqués = réservations perdues",
    "sector.restaurants.challenge2": "Questions répétitives sur le menu et allergènes",
    "sector.restaurants.challenge3": "Gestion du rush pendant les services",
    "sector.restaurants.challenges.title1": "Les défis de la",
    "sector.restaurants.challenges.highlight": "restauration",
    "sector.restaurants.challenges.description": "La restauration demande réactivité et organisation pour satisfaire chaque client.",
    "sector.restaurants.solutions.title1": "Nos",
    "sector.restaurants.solutions.highlight": "solutions",
    "sector.restaurants.solution1.title": "Gestion des réservations",
    "sector.restaurants.solution1.desc": "Acceptez les réservations 24h/24, même pendant le service.",
    "sector.restaurants.solution2.title": "Présentation du menu",
    "sector.restaurants.solution2.desc": "Répondez aux questions sur les plats et allergènes.",
    "sector.restaurants.solution3.title": "Commandes à emporter",
    "sector.restaurants.solution3.desc": "Facilitez les commandes en click & collect.",
    "sector.restaurants.stat1.value": "+50%",
    "sector.restaurants.stat1.label": "Réservations",
    "sector.restaurants.stat2.value": "0",
    "sector.restaurants.stat2.label": "Appels manqués",
    "sector.restaurants.stat3.value": "5min",
    "sector.restaurants.stat3.label": "Temps de réponse moyen",
    "sector.restaurants.video.title": "Botler™ en restauration",
    "sector.restaurants.testimonial.text": "Nos réservations ont augmenté de 50% grâce à la disponibilité permanente de Botler™.",
    "sector.restaurants.testimonial.author": "Restaurant Le Gourmet",
    "sector.restaurants.testimonial.role": "Chef propriétaire",

    // Sector Pages - Boulangerie
    "sector.boulangerie.badge": "Solution Boulangerie",
    "sector.boulangerie.title1": "Botler™ pour la",
    "sector.boulangerie.highlight": "Boulangerie",
    "sector.boulangerie.description": "Le vendeur virtuel idéal pour présenter vos produits et prendre les commandes.",
    "sector.boulangerie.challenge1": "File d'attente qui décourage les clients",
    "sector.boulangerie.challenge2": "Commandes spéciales difficiles à gérer",
    "sector.boulangerie.challenge3": "Produits non vendus en fin de journée",
    "sector.boulangerie.challenges.title1": "Les défis de la",
    "sector.boulangerie.challenges.highlight": "boulangerie",
    "sector.boulangerie.challenges.description": "La boulangerie artisanale doit conjuguer qualité et efficacité.",
    "sector.boulangerie.solutions.title1": "Nos",
    "sector.boulangerie.solutions.highlight": "solutions",
    "sector.boulangerie.solution1.title": "Catalogue produits",
    "sector.boulangerie.solution1.desc": "Présentez tous vos pains et viennoiseries.",
    "sector.boulangerie.solution2.title": "Prise de commandes",
    "sector.boulangerie.solution2.desc": "Commandes en ligne pour retrait en boutique.",
    "sector.boulangerie.solution3.title": "Horaires et disponibilités",
    "sector.boulangerie.solution3.desc": "Informez sur les produits disponibles en temps réel.",
    "sector.boulangerie.stat1.value": "+30%",
    "sector.boulangerie.stat1.label": "Commandes en ligne",
    "sector.boulangerie.stat2.value": "-20%",
    "sector.boulangerie.stat2.label": "Invendus",
    "sector.boulangerie.stat3.value": "100%",
    "sector.boulangerie.stat3.label": "Clients satisfaits",
    "sector.boulangerie.video.title": "Botler™ en boulangerie",
    "sector.boulangerie.testimonial.text": "Les commandes en ligne ont augmenté de 30% et nos invendus ont diminué de 20%.",
    "sector.boulangerie.testimonial.author": "Boulangerie du Coin",
    "sector.boulangerie.testimonial.role": "Artisan boulanger",

    // Sector Pages - Immobilier
    "sector.immobilier.badge": "Solution Immobilier",
    "sector.immobilier.title1": "Botler™ pour l'",
    "sector.immobilier.highlight": "Immobilier",
    "sector.immobilier.description": "Votre agent virtuel pour qualifier vos prospects et présenter vos biens 24h/24.",
    "sector.immobilier.challenge1": "Prospects non qualifiés qui font perdre du temps",
    "sector.immobilier.challenge2": "Demandes d'information en dehors des heures de bureau",
    "sector.immobilier.challenge3": "Visites inutiles pour des biens non adaptés",
    "sector.immobilier.challenges.title1": "Les défis de l'",
    "sector.immobilier.challenges.highlight": "immobilier",
    "sector.immobilier.challenges.description": "L'immobilier nécessite réactivité et qualification précise des prospects.",
    "sector.immobilier.solutions.title1": "Nos",
    "sector.immobilier.solutions.highlight": "solutions",
    "sector.immobilier.solution1.title": "Qualification prospects",
    "sector.immobilier.solution1.desc": "Identifiez les acheteurs sérieux automatiquement.",
    "sector.immobilier.solution2.title": "Présentation des biens",
    "sector.immobilier.solution2.desc": "Répondez aux questions sur chaque propriété.",
    "sector.immobilier.solution3.title": "Prise de rendez-vous",
    "sector.immobilier.solution3.desc": "Planifiez les visites directement dans votre agenda.",
    "sector.immobilier.stat1.value": "+45%",
    "sector.immobilier.stat1.label": "Contacts qualifiés",
    "sector.immobilier.stat2.value": "2x",
    "sector.immobilier.stat2.label": "Plus de visites utiles",
    "sector.immobilier.stat3.value": "24/7",
    "sector.immobilier.stat3.label": "Disponibilité",
    "sector.immobilier.video.title": "Botler™ en immobilier",
    "sector.immobilier.testimonial.text": "Nos contacts qualifiés ont augmenté de 45% et nos visites sont beaucoup plus efficaces.",
    "sector.immobilier.testimonial.author": "Agence Immo Plus",
    "sector.immobilier.testimonial.role": "Directeur d'agence",

    // Sector Pages - Hébergements
    "sector.hebergements.badge": "Solution Hébergements",
    "sector.hebergements.title1": "Botler™ pour les",
    "sector.hebergements.highlight": "Hébergements",
    "sector.hebergements.description": "Votre concierge virtuel pour accompagner vos clients voyageurs avant, pendant et après leur séjour.",
    "sector.hebergements.challenge1": "Questions répétitives des clients (WiFi, check-in...)",
    "sector.hebergements.challenge2": "Demandes en dehors des heures de réception",
    "sector.hebergements.challenge3": "Difficulté à personnaliser l'expérience client",
    "sector.hebergements.challenges.title1": "Les défis de l'",
    "sector.hebergements.challenges.highlight": "hébergement",
    "sector.hebergements.challenges.description": "L'hébergement demande disponibilité et personnalisation pour chaque voyageur.",
    "sector.hebergements.solutions.title1": "Nos",
    "sector.hebergements.solutions.highlight": "solutions",
    "sector.hebergements.solution1.title": "Informations séjour",
    "sector.hebergements.solution1.desc": "Répondez aux questions sur le WiFi, parking, check-in...",
    "sector.hebergements.solution2.title": "Services disponibles",
    "sector.hebergements.solution2.desc": "Présentez le petit-déjeuner, spa, room service...",
    "sector.hebergements.solution3.title": "Recommandations locales",
    "sector.hebergements.solution3.desc": "Suggérez restaurants, activités et sites à visiter.",
    "sector.hebergements.stat1.value": "+35%",
    "sector.hebergements.stat1.label": "Réservations directes",
    "sector.hebergements.stat2.value": "+40%",
    "sector.hebergements.stat2.label": "Satisfaction client",
    "sector.hebergements.stat3.value": "90%",
    "sector.hebergements.stat3.label": "Questions résolues",
    "sector.hebergements.video.title": "Botler™ pour l'hébergement",
    "sector.hebergements.testimonial.text": "Botler™ a révolutionné notre accueil. +40% de satisfaction et une disponibilité 24h/24.",
    "sector.hebergements.testimonial.author": "Hôtel du Phare",
    "sector.hebergements.testimonial.role": "Directeur",

    // Home Hero Section
    "home.hero.tagline": "La transition numérique, c'est pour tout le monde",
    "home.hero.title1": "Des outils digitaux de pro.",
    "home.hero.title2": "À des prix",
    "home.hero.title3": "imbattables.",
    "home.hero.description": "Sites web, chatbots, applications mobiles, vidéos 360°, podcasts et musiques personnalisées - créés avec l'IA, livrés en quelques jours, accessibles à tous.",
    "home.hero.baseline": "Botler360, c'est la technologie sans complexité.",
    "home.hero.badge1": "Installation en 5 minutes",
    "home.hero.badge2": "Automatisation intelligente",
    "home.hero.badge3": "Personnalisation complète",
    "home.hero.badge4": "Équipe support 9h-18h",
    "home.trust.compatible": "Compatible Shopify, WordPress, etc.",
    "home.trust.secure": "100% sécurisé, hébergé en Europe",
    "home.trust.pme": "Idéal PME",
    "home.hero.cta1": "Voir les démos",
    "home.hero.cta2": "Récupérez mon chatbot",
    "home.hero.stat": "15 heures",
    "home.hero.statLabel": "économisées",
    "home.hero.statSub": "par semaine",

    // Home Expertises Section (6 Products)
    "home.expertises.title1": "Nos",
    "home.expertises.highlight": "expertises",
    "home.expertises.title2": "",
    "home.expertises.description": "6 solutions digitales pour transformer votre activité",
    "home.expertises.chatbot.title": "Chatbots intelligents",
    "home.expertises.chatbot.desc": "Des assistants virtuels pour répondre 24h/24, automatiser et booster vos conversions.",
    "home.expertises.chatbot.price": "À partir de 9€/mois",
    "home.expertises.website.title": "Sites web professionnels",
    "home.expertises.website.desc": "Sites vitrines, e-commerce, landing pages... créés avec l'IA, optimisés SEO & mobile.",
    "home.expertises.website.price": "249€ tout inclus",
    "home.expertises.mobile.title": "Applications mobiles",
    "home.expertises.mobile.desc": "Apps iOS & Android pour gérer votre business et fidéliser vos clients.",
    "home.expertises.mobile.price": "249€",
    "home.expertises.video360.title": "Vidéos 360° immersives",
    "home.expertises.video360.desc": "Visites virtuelles pour hôtels, restaurants, musées - une expérience immersive.",
    "home.expertises.video360.price": "À partir de 125€",
    "home.expertises.audio.title": "Musiques & podcasts",
    "home.expertises.audio.desc": "Identité sonore sur-mesure : musiques d'ambiance, annonces, podcasts brandés.",
    "home.expertises.audio.price": "À partir de 5€",
    "home.expertises.custom.title": "Projets sur-mesure",
    "home.expertises.custom.desc": "Dashboards, automatisations, outils métier : on concrétise votre idée avec l'IA.",
    "home.expertises.custom.price": "Sur devis",
    "home.expertises.cta": "En savoir plus",

    // Home Value Pillars Section
    "home.pillars.title1": "Nos",
    "home.pillars.highlight": "3 piliers",
    "home.pillars.title2": "de valeur",
    "home.pillars.speed.title": "Rapidité",
    "home.pillars.speed.desc": "Nos outils sont prêts en quelques jours, pas en plusieurs semaines.",
    "home.pillars.simplicity.title": "Simplicité",
    "home.pillars.simplicity.desc": "On rend la tech simple, même pour ceux qui n'y connaissent rien.",
    "home.pillars.accessibility.title": "Accessibilité",
    "home.pillars.accessibility.desc": "Parce que tout le monde devrait accéder aux outils digitaux, peu importe le budget.",

    // Home Stats Section
    "home.stats.title1": "Automatisez",
    "home.stats.title2": "de vos réponses client",
    "home.stats.description": "Libérez votre équipe des questions répétitives pour qu'elle se concentre sur les tâches à forte valeur ajoutée.",
    "home.stats.card.title1": "Plus de",
    "home.stats.card.title2": "des consommateurs préfèrent échanger avec un chatbot plutôt que par téléphone.",
    "home.stats.card.description": "Avec Botler™, évitez que vos visiteurs quittent le site web faute d'obtenir rapidement une réponse à leurs questions.",
    "home.stats.card.highlight": "Ne perdez plus 50% de clients potentiels",
    
    // Home Features Section
    "home.features.title1": "Botler™, le chatbot pensé pour",
    "home.features.highlight": "booster",
    "home.features.title2": "votre relation client",
    "home.features.description": "Déployez rapidement un assistant conversationnel sur votre site web et gagnez en efficacité.",
    "home.features.install.title": "Installation en 5 minutes",
    "home.features.install.desc": "Déployez rapidement un assistant conversationnel sur votre site web et gagnez en efficacité.",
    "home.features.available.title": "Disponible 24h/24",
    "home.features.available.desc": "Répondez instantanément aux questions de vos visiteurs 24h/24 et 7j/7.",
    "home.features.qualify.title": "Qualification automatique",
    "home.features.qualify.desc": "Qualifiez automatiquement vos prospects et augmentez vos conversions.",
    
    // Home Sectors Section
    "home.sectors.title1": "Des solutions",
    "home.sectors.highlight": "adaptées",
    "home.sectors.title2": "à votre métier",
    "home.sectors.description": "Chaque secteur d'activité a ses propres défis. Botler™ a développé des chatbots intelligents qui maîtrisent parfaitement les spécificités de votre domaine.",
    "home.sectors.botlerSays": "Moi c'est Botler™ : vous voulez savoir de quoi je suis capable ?",
    "home.sectors.viewDemos": "Voir les démos",
    "home.sectors.tourism.desc": "Guide virtuel pour vos visiteurs",
    "home.sectors.tourism.stat": "+40% de satisfaction",
    "home.sectors.viticulture.desc": "Sommelier virtuel pour conseils œnologiques",
    "home.sectors.viticulture.stat": "+35% de ventes",
    "home.sectors.restaurants.desc": "Votre meilleur assistant restaurateur 24h/24",
    "home.sectors.restaurants.stat": "+50% de réservations",
    "home.sectors.bakery.desc": "Le vendeur en boulangerie que vous rêvez",
    "home.sectors.bakery.stat": "+30% de commandes",
    "home.sectors.realEstate.desc": "Votre agent virtuel pour mieux qualifier vos futurs clients",
    "home.sectors.realEstate.stat": "+45% de contacts",
    "home.sectors.accommodation.desc": "Concierge virtuel pour vos clients",
    "home.sectors.accommodation.stat": "+35% de réservations",
    
    // Home Testimonials Section
    "home.testimonials.title1": "Ce que nos",
    "home.testimonials.highlight": "clients",
    "home.testimonials.title2": "disent",
    "home.testimonials.description": "Découvrez comment Botler™ transforme leur relation client",
    "home.testimonials.1.text": "Botler™ a révolutionné notre accueil visiteur. +40% de satisfaction client et une disponibilité 24h/24 qui fait la différence.",
    "home.testimonials.1.author": "Hotel du Phare",
    "home.testimonials.1.sector": "Hébergement",
    "home.testimonials.1.stat": "+40% de satisfaction client",
    "home.testimonials.2.text": "Nos réservations ont augmenté de 35% grâce à la disponibilité permanente de Botler™. Plus aucune perte d'opportunité !",
    "home.testimonials.2.author": "Restaurant Le Gourmet",
    "home.testimonials.2.sector": "Restauration",
    "home.testimonials.2.stat": "+35% de réservations",
    "home.testimonials.3.text": "Botler™ nous fait économiser 15 heures par semaine en répondant aux questions récurrentes de nos clients.",
    "home.testimonials.3.author": "Domaine des Vignes",
    "home.testimonials.3.sector": "Viticulture",
    "home.testimonials.3.stat": "15h économisées/semaine",
    
    // CTA Section
    "cta.title1": "Rejoignez les entreprises qui ont déjà",
    "cta.highlight": "révolutionné",
    "cta.title2": "leur relation client avec Botler™.",
    "cta.description": "Déployez votre chatbot en moins de 5 minutes et commencez à améliorer votre relation client dès aujourd'hui.",
    "cta.button": "Récupérez mon chatbot",
    
    // Footer
    "footer.description": "Des chatbots intelligents adaptés à votre secteur d'activité pour révolutionner votre relation client.",
    "footer.company": "Entreprise",
    "footer.location": "France, Royaume-Uni, Tunisie & Indonésie",
    "footer.legal": "Mentions légales",
    "footer.cgv": "CGV",
    "footer.privacy": "Politique de confidentialité",
    "footer.cookies": "Politique de cookies",
    "footer.rights": "Tous droits réservés.",
    "footer.tagline": "Créé avec passion pour révolutionner votre relation client.",
    "footer.trust.humanTeam": "Derrière nos outils IA, il y a une équipe humaine.",
    "footer.trust.support": "On vous accompagne à chaque étape.",
    "footer.trust.location": "Équipe basée en France, UK, Tunisie & Indonésie",
    "footer.trust.ethical": "IA éthique et transparente",
    "footer.trust.ownership": "Vous gardez 100% la propriété de vos outils.",
    "footer.trust.smile": "Botler360, c'est la technologie avec le sourire.",
    
    // Demo Page
    "demo.title1": "Découvrez Botler™",
    "demo.highlight": "en action",
    "demo.description": "Explorez nos démonstrations vidéo pour chaque secteur d'activité et découvrez comment Botler™ peut transformer votre relation client.",
    "demo.selectSector": "Sélectionnez un secteur",
    "demo.watchVideo": "Regarder la vidéo",
    "demo.features": "Fonctionnalités clés",
    "demo.noVideo": "Vidéo bientôt disponible",
    "demo.categorySectors": "Démos par Secteur",
    "demo.categoryProducts": "Démos par Produit",
    "demo.allSectorDemos": "Toutes les démos secteur",
    "demo.allProductDemos": "Toutes les démos produit",
    "demo.productLabel": "Solution Botler360",
    "demo.learnMore": "En savoir plus",
    "demo.tourism.name": "Tourisme",
    "demo.tourism.description": "Découvrez comment Botler™ guide vos visiteurs et répond à toutes leurs questions sur votre destination.",
    "demo.tourism.feature1": "Recommandations personnalisées",
    "demo.tourism.feature2": "Support multilingue",
    "demo.tourism.feature3": "Disponible 24h/24",
    "demo.viticulture.name": "Viticulture",
    "demo.viticulture.description": "Votre sommelier virtuel conseille vos clients sur les accords mets-vins et vos cuvées.",
    "demo.viticulture.feature1": "Conseils œnologiques",
    "demo.viticulture.feature2": "Réservation de visites",
    "demo.viticulture.feature3": "Présentation des cuvées",
    "demo.restaurants.name": "Restaurants",
    "demo.restaurants.description": "Botler™ gère vos réservations et présente votre carte à vos clients gourmets.",
    "demo.restaurants.feature1": "Gestion des réservations",
    "demo.restaurants.feature2": "Présentation du menu",
    "demo.restaurants.feature3": "Informations allergènes",
    "demo.bakery.name": "Boulangerie",
    "demo.bakery.description": "Le vendeur virtuel idéal pour présenter vos produits et prendre les commandes.",
    "demo.bakery.feature1": "Catalogue produits",
    "demo.bakery.feature2": "Prise de commandes",
    "demo.bakery.feature3": "Horaires et disponibilités",
    "demo.realEstate.name": "Immobilier",
    "demo.realEstate.description": "Qualifiez automatiquement vos prospects et présentez vos biens immobiliers.",
    "demo.realEstate.feature1": "Qualification prospects",
    "demo.realEstate.feature2": "Présentation des biens",
    "demo.realEstate.feature3": "Prise de rendez-vous",
    "demo.accommodation.name": "Hébergements",
    "demo.accommodation.description": "Votre concierge virtuel répond aux questions de vos clients voyageurs.",
    "demo.accommodation.feature1": "Informations séjour",
    "demo.accommodation.feature2": "Services disponibles",
    "demo.accommodation.feature3": "Recommandations locales",
    "demo.boutiques.name": "Boutiques & Commerces",
    "demo.boutiques.description": "Découvrez comment Botler™ accompagne vos clients en boutique et booste vos ventes.",
    "demo.boutiques.feature1": "Catalogue produits interactif",
    "demo.boutiques.feature2": "Click & collect automatisé",
    "demo.boutiques.feature3": "Programme fidélité intégré",
    "demo.websites.name": "Sites Web Professionnels",
    "demo.websites.description": "Explorez nos sites web clé en main avec chatbot intégré pour convertir vos visiteurs.",
    "demo.websites.fullDescription": "Découvrez comment Botler360 crée des sites vitrines modernes, optimisés SEO et livrés clé en main en quelques jours pour seulement 249€. Idéal pour les indépendants, artisans et PME.",
    "demo.websites.feature1": "Design moderne et responsive",
    "demo.websites.feature2": "Chatbot intégré offert",
    "demo.websites.feature3": "Optimisation SEO incluse",
    "demo.websites.feature4": "Hébergement et maintenance compris",
    "demo.ecommerce.name": "Boutiques E-commerce",
    "demo.ecommerce.description": "Voyez comment nos solutions permettent de vendre vos produits en ligne facilement, avec gestion des stocks, paiement sécurisé et une expérience client optimisée.",
    "demo.ecommerce.feature1": "Paiement en ligne sécurisé",
    "demo.ecommerce.feature2": "Gestion de stock intégrée",
    "demo.ecommerce.feature3": "Click & Collect disponible",
    "demo.ecommerce.feature4": "Vente assistée via Chatbot",
    "demo.stats.clients": "Clients satisfaits",
    "demo.stats.hours": "Service client économisé",
    "demo.stats.satisfaction": "Satisfaction client",
    
    // Solutions Page
    "solutions.title1": "Nos",
    "solutions.highlight": "Solutions Digitales",
    "solutions.description": "Développez votre présence en ligne avec nos solutions sur mesure, conçues pour booster votre activité.",
    "solutions.pricing.title1": "Tarifs",
    "solutions.pricing.highlight": "Chatbot",
    "solutions.pricing.subtitle": "Tarifs transparents et adaptés à vos besoins",
    "solutions.pricing.perMonth": "/mois",
    "solutions.pricing.recommended": "Recommandé",
    "solutions.pricing.commission": "1% de commission sur chaque vente effectuée entièrement avec Botler (Packs Expert et Expert PME)",
    
    // Pack Junior
    "solutions.pricing.junior.desc": "Pour tous types d'entreprises",
    "solutions.pricing.junior.f1": "Installation rapide",
    "solutions.pricing.junior.f2": "Personnalisé à votre charte graphique",
    "solutions.pricing.junior.f3": "Réponses sur-mesure aux questions visiteurs",
    "solutions.pricing.junior.f4": "Multi-langues",
    "solutions.pricing.junior.cta": "Commencer",
    
    // Pack Expert
    "solutions.pricing.expert.desc": "Parfait pour indépendants et micro-équipes",
    "solutions.pricing.expert.f1": "Matching intelligent sur base de données ciblée",
    "solutions.pricing.expert.f2": "Installation simple et rapide",
    "solutions.pricing.expert.f3": "Personnalisé à votre charte graphique",
    "solutions.pricing.expert.f4": "Assistant commercial intégré (prospects, alertes email, prise de RDV)",
    "solutions.pricing.expert.f5": "Multilingue",
    "solutions.pricing.expert.f6": "Solution clé en main pour générer vos premiers leads",
    "solutions.pricing.expert.cta": "Choisir Expert",
    
    // Pack Expert PME
    "solutions.pricing.expertPME.desc": "Conçu pour les PME en croissance",
    "solutions.pricing.expertPME.f1": "Pensé pour les petites et moyennes entreprises",
    "solutions.pricing.expertPME.f2": "Filtrage intelligent + matching avancé",
    "solutions.pricing.expertPME.f3": "Optimisé pour un contenu volumineux",
    "solutions.pricing.expertPME.f4": "Personnalisé à votre image et multilingue",
    "solutions.pricing.expertPME.f5": "Assistant commercial avec alertes et création auto de prospects",
    "solutions.pricing.expertPME.f6": "Bot robuste pour gérer un volume important de demandes",
    "solutions.pricing.expertPME.cta": "Choisir Expert PME",
    
    // Pack Custom
    "solutions.pricing.custom.name": "Demande ou besoin spécifique ?",
    "solutions.pricing.custom.price": "Sur devis",
    "solutions.pricing.custom.desc": "Solution personnalisée selon vos besoins spécifiques",
    "solutions.pricing.custom.f1": "Accompagnement sur-mesure",
    "solutions.pricing.custom.f2": "Fonctionnalités avancées à la carte",
    "solutions.pricing.custom.cta": "Nous contacter",
    "solutions.guarantees.satisfaction.title": "Satisfaction garantie",
    "solutions.guarantees.satisfaction.desc": "30 jours d'essai gratuit",
    "solutions.guarantees.deploy.title": "Déploiement rapide",
    "solutions.guarantees.deploy.desc": "En ligne en 24h maximum",
    "solutions.guarantees.support.title": "Support expert",
    "solutions.guarantees.support.desc": "Équipe dédiée à votre succès",
    "solutions.website.badge": "Offre Spéciale",
    "solutions.website.title": "Site Web Vitrine Professionnel",
    "solutions.website.description": "Une solution complète pour créer votre présence en ligne professionnelle rapidement et efficacement.",
    "solutions.website.h1": "Livraison en 24h",
    "solutions.website.h2": "Design responsive",
    "solutions.website.h3": "Hébergement inclus",
    "solutions.website.h4": "Compatible mobile",
    "solutions.website.f1": "Design moderne et responsive",
    "solutions.website.f2": "Hébergement web sécurisé",
    "solutions.website.f3": "Certificat SSL gratuit",
    "solutions.website.f4": "Optimisation SEO de base",
    "solutions.website.f5": "Formulaire de contact",
    "solutions.website.f6": "Intégration réseaux sociaux",
    "solutions.website.f7": "Support technique 30 jours",
    "solutions.website.f8": "Formation à l'utilisation",
    "solutions.website.f9": "Sauvegarde automatique",
    "solutions.website.f10": "Statistiques de visite",
    "solutions.website.included": "Ce qui est inclus",
    "solutions.website.cta": "Commander maintenant",
    "solutions.additional.title1": "Autres",
    "solutions.additional.highlight": "Solutions",
    "solutions.additional.description": "Complétez votre présence digitale avec nos services additionnels",
    "solutions.additional.mobile.title": "Application Mobile",
    "solutions.additional.mobile.desc": "App iOS et Android sur mesure pour votre entreprise",
    "solutions.additional.video360.title": "Vidéos 360° immersives",
    "solutions.additional.video360.desc": "Visites virtuelles pour hôtels, restaurants, musées - une expérience immersive",
    "solutions.additional.video360.price": "À partir de 125€",
    "solutions.additional.audio.title": "Musiques & podcasts",
    "solutions.additional.audio.desc": "Identité sonore sur-mesure : musiques d'ambiance, annonces, podcasts brandés",
    "solutions.additional.audio.price": "À partir de 5€",
    "solutions.additional.custom.title": "Projets sur-mesure",
    "solutions.additional.custom.desc": "Dashboards, automatisations, outils métier : on concrétise votre idée avec l'IA.",
    "solutions.additional.custom.price": "Sur devis",

    // Websites Page
    "websites.badge": "Site Web Professionnel",
    "websites.title1": "Votre site web professionnel.",
    "websites.highlight": "Clé en main.",
    "websites.title2": "249€ tout compris... à vie.",
    "websites.description": "Un site web moderne, optimisé SEO et mobile, créé avec l'IA et livré en 24-48h.",
    "websites.priceLabel": "tout inclus, paiement unique",
    "websites.highlight1": "Livraison 24-48h",
    "websites.highlight2": "Design responsive",
    "websites.highlight3": "Hébergement inclus",
    "websites.highlight4": "Compatible mobile",
    "websites.cta": "Commander mon site",
    "websites.bonus.title": "Bonus : Chatbot intégré offert le premier mois !",
    "websites.bonus.description": "Chaque site web inclut un chatbot Botler™ gratuit pendant 30 jours pour booster vos conversions.",
    "websites.points.title1": "Pourquoi choisir",
    "websites.points.highlight": "Botler360 ?",
    "websites.point1.title": "Ne vous cachez plus",
    "websites.point1.desc": "Ayez enfin une présence en ligne professionnelle qui vous représente.",
    "websites.point2.title": "Soyez visible",
    "websites.point2.desc": "Site optimisé SEO pour être trouvé sur Google par vos futurs clients.",
    "websites.point3.title": "Créez des opportunités",
    "websites.point3.desc": "Transformez les visiteurs en clients avec un site qui convertit.",
    "websites.point4.title": "Zéro effort",
    "websites.point4.desc": "On s'occupe de tout : design, développement, hébergement, maintenance.",
    "websites.features.title": "Tout ce qui est inclus",
    "websites.feature1": "Design moderne et responsive",
    "websites.feature2": "Hébergement web sécurisé",
    "websites.feature3": "Certificat SSL gratuit (HTTPS)",
    "websites.feature4": "Optimisation SEO de base",
    "websites.feature5": "Formulaire de contact",
    "websites.feature6": "Intégration réseaux sociaux",
    "websites.feature7": "Support technique 30 jours",
    "websites.feature8": "Formation à l'utilisation",
    "websites.feature9": "Sauvegarde automatique",
    "websites.feature10": "Statistiques de visite",
    "websites.compare.title1": "Comparez et",
    "websites.compare.highlight": "économisez",
    "websites.compare.price": "Prix",
    "websites.compare.delivery": "Délai",
    "websites.compare.hosting": "Hébergement inclus",
    "websites.compare.seo": "Optimisation SEO",
    "websites.compare.support": "Support",
    "websites.compare.chatbot": "Chatbot intégré",
    "websites.compare.diy": "DIY",
    "websites.compare.free1month": "1 mois offert",
    "websites.cta.title1": "Prêt à lancer",
    "websites.cta.highlight": "votre site ?",
    "websites.cta.description": "Commandez maintenant et recevez votre site professionnel en 24-48h.",
    "websites.cta.button": "Commander maintenant",

    // Mobile Apps Page
    "mobileapps.badge": "Application Mobile",
    "mobileapps.title1": "Votre application mobile,",
    "mobileapps.highlight": "prête en 7 jours.",
    "mobileapps.title2": "Pour seulement 249€.",
    "mobileapps.description": "Une app iOS & Android personnalisée pour gérer votre business et fidéliser vos clients.",
    "mobileapps.priceLabel": "tout inclus",
    "mobileapps.highlight1": "iOS & Android",
    "mobileapps.highlight2": "Livraison 7 jours",
    "mobileapps.highlight3": "Publication stores",
    "mobileapps.highlight4": "Design personnalisé",
    "mobileapps.cta": "Commander mon app",
    "mobileapps.points.title1": "Pourquoi une",
    "mobileapps.points.highlight": "app mobile ?",
    "mobileapps.point1.title": "L'app la moins chère",
    "mobileapps.point1.desc": "249€ au lieu de 5000€+ en agence traditionnelle.",
    "mobileapps.point2.title": "Livraison express",
    "mobileapps.point2.desc": "Votre app prête en 7 jours, pas en plusieurs mois.",
    "mobileapps.point3.title": "Transparence totale",
    "mobileapps.point3.desc": "Prix fixe, pas de surprises ni de frais cachés.",
    "mobileapps.point4.title": "Zéro risque",
    "mobileapps.point4.desc": "Satisfait ou remboursé pendant 30 jours.",
    "mobileapps.features.title": "13 fonctionnalités incluses",
    "mobileapps.feature1": "Design personnalisé à votre image",
    "mobileapps.feature2": "Compatible iOS et Android",
    "mobileapps.feature3": "Notifications push",
    "mobileapps.feature4": "Catalogue produits/services",
    "mobileapps.feature5": "Système de réservation",
    "mobileapps.feature6": "Programme de fidélité",
    "mobileapps.feature7": "Paiement en ligne intégré",
    "mobileapps.feature8": "Messagerie intégrée",
    "mobileapps.feature9": "Géolocalisation",
    "mobileapps.feature10": "Mode hors-ligne",
    "mobileapps.feature11": "Statistiques d'utilisation",
    "mobileapps.feature12": "Mises à jour gratuites 1 an",
    "mobileapps.feature13": "Support technique dédié",
    "mobileapps.process.title1": "Un processus",
    "mobileapps.process.highlight": "simple en 3 étapes",
    "mobileapps.process.step1.title": "1. Briefing",
    "mobileapps.process.step1.desc": "Vous nous décrivez vos besoins et votre identité visuelle.",
    "mobileapps.process.step2.title": "2. Développement",
    "mobileapps.process.step2.desc": "Notre équipe crée votre app avec l'IA en 5-7 jours.",
    "mobileapps.process.step3.title": "3. Livraison",
    "mobileapps.process.step3.desc": "Publication sur App Store et Google Play incluse.",
    "mobileapps.faq.title": "Questions fréquentes",
    "mobileapps.faq.q1": "L'app est-elle vraiment à moi ?",
    "mobileapps.faq.a1": "Oui, vous êtes 100% propriétaire de votre application.",
    "mobileapps.faq.q2": "Quels sont les frais récurrents ?",
    "mobileapps.faq.a2": "Aucun frais caché. Seuls les frais des stores (Apple 99€/an, Google 25€ une fois) s'appliquent.",
    "mobileapps.faq.q3": "Puis-je modifier l'app après livraison ?",
    "mobileapps.faq.a3": "Oui, les mises à jour de contenu sont gratuites pendant 1 an.",
    "mobileapps.faq.q4": "Comment se passe le support ?",
    "mobileapps.faq.a4": "Vous bénéficiez d'un support technique dédié par email pendant 1 an.",
    "mobileapps.cta.title1": "Prêt à lancer",
    "mobileapps.cta.highlight": "votre app ?",
    "mobileapps.cta.description": "Commandez maintenant et recevez votre application en 7 jours.",
    "mobileapps.cta.button": "Commander maintenant",

    // FAQ Page
    "faq.title1": "Questions",
    "faq.highlight": "fréquentes",
    "faq.description": "Retrouvez les réponses aux questions les plus posées sur nos chatbots et nos services de création de sites web.",
    "faq.categoryChatbots": "FAQ Chatbots",
    "faq.categoryWebsites": "FAQ Sites Web",
    "faq.cta.title": "Vous n'avez pas trouvé votre réponse ?",
    "faq.cta.description": "Notre équipe est là pour vous aider. Contactez-nous et nous répondrons à toutes vos questions.",
    "faq.cta.button": "Nous contacter",

    // Contact Page
    "contact.title1": "Contactez",
    "contact.highlight": "notre équipe",
    "contact.description": "Discutons de votre projet et découvrez comment Botler™ peut transformer votre relation client.",
    "contact.form.title": "Envoyez-nous un message",
    "contact.form.firstName": "Prénom",
    "contact.form.firstNamePlaceholder": "Votre prénom",
    "contact.form.lastName": "Nom",
    "contact.form.lastNamePlaceholder": "Votre nom",
    "contact.form.optional": "optionnel",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "votre@email.com",
    "contact.form.company": "Entreprise",
    "contact.form.companyPlaceholder": "Nom de votre entreprise",
    "contact.form.sector": "Secteur d'activité",
    "contact.form.sectorPlaceholder": "Sélectionnez un secteur",
    "contact.form.other": "Autre",
    "contact.form.projectType": "Type de projet",
    "contact.form.projectTypePlaceholder": "Sélectionnez un type de projet",
    "contact.form.projectType.chatbot": "Chatbot",
    "contact.form.projectType.website": "Site web",
    "contact.form.projectType.websiteChatbot": "Site web + Chatbot",
    "contact.form.projectType.mobileApp": "Application Mobile",
    "contact.form.projectType.video360": "Vidéo 360°",
    "contact.form.projectType.musicPodcast": "Musique / Podcast",
    "contact.form.projectType.custom": "Projet sur-mesure",
    "contact.form.phone": "Téléphone",
    "contact.form.phonePlaceholder": "+33 6 00 00 00 00",
    "contact.form.attachment": "Joindre un dossier",
    "contact.form.attachmentPlaceholder": "Télécharger un fichier (PDF, DOC, image)",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Décrivez votre projet...",
    "contact.form.submit": "Envoyer le message",
    "contact.form.sending": "Envoi en cours...",
    "contact.form.success": "Message envoyé avec succès ! Nous vous répondrons sous 24h.",
    "contact.form.error": "Une erreur est survenue. Veuillez réessayer.",
    "contact.form.surpriseMe": "Surprenez-moi !",
    "contact.form.surpriseSuccess": "Demande envoyée ! Notre équipe va vous préparer une proposition sur-mesure.",
    "contact.form.fileTooLarge": "Le fichier est trop volumineux (max 10 Mo).",
    "contact.info.title": "Nos coordonnées",
    "contact.info.phone": "Téléphone",
    "contact.info.email": "Email",
    "contact.info.location": "Localisation",
    "contact.benefits.title": "Pourquoi nous contacter ?",
    "contact.benefits.fast.title": "Réponse rapide",
    "contact.benefits.fast.desc": "Notre équipe vous répond sous 24h",
    "contact.benefits.personal.title": "Accompagnement personnalisé",
    "contact.benefits.personal.desc": "Un expert dédié à votre projet",
    "contact.benefits.free.title": "Devis gratuit",
    "contact.benefits.free.desc": "Sans engagement de votre part",
    "contact.mascot": "Notre équipe est là pour vous accompagner dans votre transformation digitale.",

    // Chat Widget
    "chat.button": "Parler à Botler",
    "chat.online": "en ligne",
    "chat.placeholder": "Écrivez votre message...",
    "chat.poweredBy": "Propulsé par Botler 360",
    "chat.welcome.title": "Bonjour ! Je suis Botler 👋",
    "chat.welcome.text": "Comment puis-je vous aider aujourd'hui ?",

    // SEO
    "seo.home.title": "Chatbot IA pour PME",
    "seo.home.description": "Botler, le chatbot IA pour les PME. Déployez un assistant intelligent sur votre site web en quelques minutes. Simple, rapide, efficace.",
    "seo.demo.title": "Démo Chatbot",
    "seo.demo.description": "Découvrez Botler en action. Testez nos chatbots IA pour le tourisme, la restauration, l'immobilier et plus encore.",
    "seo.contact.title": "Contact",
    "seo.contact.description": "Contactez l'équipe Botler 360. Nous répondons sous 24h pour discuter de votre projet chatbot ou site web.",
    "seo.solutions.title": "Nos Solutions et Tarifs",
    "seo.solutions.description": "Découvrez nos packs chatbot IA à partir de 29€/mois. Sites web à 249€. Solutions sur mesure pour chaque entreprise.",
    "seo.faq.title": "FAQ",
    "seo.faq.description": "Toutes vos questions sur les chatbots IA et la création de sites web. Réponses claires et détaillées.",
    "seo.websites.title": "Création de Sites Web",
    "seo.websites.description": "Site web professionnel à 249€. Design moderne, optimisé SEO, avec chatbot IA intégré.",
    "seo.mobileapps.title": "Applications Mobiles",
    "seo.mobileapps.description": "Application mobile iOS et Android à 249€. Rapide, performante, avec toutes les fonctionnalités essentielles.",
    "seo.sector.tourisme.title": "Chatbot IA pour le Tourisme",
    "seo.sector.tourisme.description": "Chatbot IA spécialisé tourisme. Répondez à vos voyageurs 24/7, gérez les réservations et qualifiez vos leads.",
    "seo.sector.viticulture.title": "Chatbot IA pour la Viticulture",
    "seo.sector.viticulture.description": "Chatbot IA pour domaines viticoles. Accueillez vos visiteurs, gérez les dégustations et vendez en ligne.",
    "seo.sector.restaurants.title": "Chatbot IA pour les Restaurants",
    "seo.sector.restaurants.description": "Chatbot IA pour restaurants. Gérez les réservations, répondez aux questions et fidélisez vos clients.",
    "seo.sector.boulangerie.title": "Chatbot IA pour les Boulangeries",
    "seo.sector.boulangerie.description": "Chatbot IA pour boulangeries et pâtisseries. Commandes en ligne, horaires, et service client automatisé.",
    "seo.sector.immobilier.title": "Chatbot IA pour l'Immobilier",
    "seo.sector.immobilier.description": "Chatbot IA pour agences immobilières. Qualifiez vos acquéreurs, planifiez les visites et répondez 24/7.",
    "seo.sector.hebergements.title": "Chatbot IA pour les Hébergements",
    "seo.sector.hebergements.description": "Chatbot IA pour hôtels et hébergements. Réservations, conciergerie et service client automatisé.",

    // Legal Pages
    "legal.mentions.title": "Mentions Légales",
    "legal.mentions.editor.title": "Éditeur du site",
    "legal.mentions.host.title": "Hébergeur",
    "legal.mentions.ip.title": "Propriété intellectuelle",
    "legal.mentions.liability.title": "Responsabilité",
    "legal.mentions.data.title": "Données personnelles",
    "legal.mentions.law.title": "Droit applicable",
    "legal.cgv.title": "Conditions Générales de Vente",
    "legal.cgv.article1.title": "Article 1 — Objet",
    "legal.cgv.article2.title": "Article 2 — Acceptation des conditions",
    "legal.cgv.article3.title": "Article 3 — Description des services",
    "legal.cgv.article4.title": "Article 4 — Tarifs et paiement",
    "legal.cgv.article5.title": "Article 5 — Durée et résiliation",
    "legal.cgv.article6.title": "Article 6 — Propriété intellectuelle",
    "legal.cgv.article7.title": "Article 7 — Responsabilité et garanties",
    "legal.cgv.article8.title": "Article 8 — Données personnelles",
    "legal.cgv.article9.title": "Article 9 — Droit de rétractation",
    "legal.cgv.article10.title": "Article 10 — Litiges",
    "legal.privacy.title": "Politique de Confidentialité",
    "legal.privacy.controller.title": "Responsable du traitement",
    "legal.privacy.collected.title": "Données collectées",
    "legal.privacy.purposes.title": "Finalités du traitement",
    "legal.privacy.legal-basis.title": "Base légale",
    "legal.privacy.recipients.title": "Destinataires des données",
    "legal.privacy.retention.title": "Durée de conservation",
    "legal.privacy.rights.title": "Vos droits",
    "legal.privacy.cookies.title": "Cookies",
    "legal.privacy.transfers.title": "Transferts hors UE",
    "legal.privacy.dpo.title": "Contact DPO",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.solutions": "Our Solutions",
    "nav.demo": "Demo",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.sectors": "Sectors",
    "nav.getStarted": "Get Started",
    
    // Sectors
    "sector.tourism": "Tourism",
    "sector.viticulture": "Viticulture",
    "sector.restaurants": "Restaurants",
    "sector.bakery": "Bakery",
    "sector.realEstate": "Real Estate",
    "sector.accommodation": "Accommodation",

    // Sector Pages - Tourism
    "sector.tourisme.badge": "Tourism Solution",
    "sector.tourisme.title1": "Botler™ for",
    "sector.tourisme.highlight": "Tourism",
    "sector.tourisme.description": "Transform your visitors' experience with a virtual assistant available 24/7, capable of answering all their questions about your destination.",
    "sector.tourisme.challenge1": "Visitors leaving without answers to their questions",
    "sector.tourisme.challenge2": "Overwhelmed team during peak season",
    "sector.tourisme.challenge3": "Difficulty communicating in multiple languages",
    "sector.tourisme.challenges.title1": "Challenges in the",
    "sector.tourisme.challenges.highlight": "tourism sector",
    "sector.tourisme.challenges.description": "Tourism faces unique availability and multilingual challenges.",
    "sector.tourisme.solutions.title1": "Our",
    "sector.tourisme.solutions.highlight": "solutions",
    "sector.tourisme.solution1.title": "Multilingual assistant",
    "sector.tourisme.solution1.desc": "Respond to your visitors in their language, automatically.",
    "sector.tourisme.solution2.title": "Available 24/7",
    "sector.tourisme.solution2.desc": "Never lose visitors, even outside opening hours.",
    "sector.tourisme.solution3.title": "Personalized recommendations",
    "sector.tourisme.solution3.desc": "Suggest the best activities based on each person's preferences.",
    "sector.tourisme.stat1.value": "+40%",
    "sector.tourisme.stat1.label": "Visitor satisfaction",
    "sector.tourisme.stat2.value": "15h",
    "sector.tourisme.stat2.label": "Saved per week",
    "sector.tourisme.stat3.value": "24/7",
    "sector.tourisme.stat3.label": "Availability",
    "sector.tourisme.video.title": "See Botler™ in action",
    "sector.tourisme.testimonial.text": "Botler™ has revolutionized our visitor reception. +40% satisfaction and 24/7 availability that makes the difference.",
    "sector.tourisme.testimonial.author": "Bordeaux Tourism Office",
    "sector.tourisme.testimonial.role": "Director",

    // Sector Pages - Viticulture
    "sector.viticulture.badge": "Viticulture Solution",
    "sector.viticulture.title1": "Botler™ for",
    "sector.viticulture.highlight": "Viticulture",
    "sector.viticulture.description": "Your virtual sommelier advises your visitors on food-wine pairings and presents your vintages with passion.",
    "sector.viticulture.challenge1": "Customers hesitating without personalized advice",
    "sector.viticulture.challenge2": "Lack of time to welcome each visitor",
    "sector.viticulture.challenge3": "Lost sales outside opening hours",
    "sector.viticulture.challenges.title1": "Challenges in",
    "sector.viticulture.challenges.highlight": "viticulture",
    "sector.viticulture.challenges.description": "The wine world requires expertise and availability to advise customers.",
    "sector.viticulture.solutions.title1": "Our",
    "sector.viticulture.solutions.highlight": "solutions",
    "sector.viticulture.solution1.title": "Virtual sommelier",
    "sector.viticulture.solution1.desc": "Personalized wine advice for each visitor.",
    "sector.viticulture.solution2.title": "Visit booking",
    "sector.viticulture.solution2.desc": "Automatically manage tasting requests.",
    "sector.viticulture.solution3.title": "Vintage presentation",
    "sector.viticulture.solution3.desc": "Showcase your production with passion.",
    "sector.viticulture.stat1.value": "+35%",
    "sector.viticulture.stat1.label": "Online sales",
    "sector.viticulture.stat2.value": "+50%",
    "sector.viticulture.stat2.label": "Visit bookings",
    "sector.viticulture.stat3.value": "8",
    "sector.viticulture.stat3.label": "Languages supported",
    "sector.viticulture.video.title": "Discover our virtual sommelier",
    "sector.viticulture.testimonial.text": "Our online sales increased by 35% thanks to Botler™'s personalized advice.",
    "sector.viticulture.testimonial.author": "Domaine des Vignes",
    "sector.viticulture.testimonial.role": "Owner",

    // Sector Pages - Restaurants
    "sector.restaurants.badge": "Restaurant Solution",
    "sector.restaurants.title1": "Botler™ for",
    "sector.restaurants.highlight": "Restaurants",
    "sector.restaurants.description": "Your best restaurant assistant 24/7 to manage reservations and present your menu.",
    "sector.restaurants.challenge1": "Missed calls = lost reservations",
    "sector.restaurants.challenge2": "Repetitive questions about the menu and allergens",
    "sector.restaurants.challenge3": "Managing the rush during service",
    "sector.restaurants.challenges.title1": "Challenges in",
    "sector.restaurants.challenges.highlight": "restaurants",
    "sector.restaurants.challenges.description": "Restaurants require responsiveness and organization to satisfy each customer.",
    "sector.restaurants.solutions.title1": "Our",
    "sector.restaurants.solutions.highlight": "solutions",
    "sector.restaurants.solution1.title": "Reservation management",
    "sector.restaurants.solution1.desc": "Accept reservations 24/7, even during service.",
    "sector.restaurants.solution2.title": "Menu presentation",
    "sector.restaurants.solution2.desc": "Answer questions about dishes and allergens.",
    "sector.restaurants.solution3.title": "Takeaway orders",
    "sector.restaurants.solution3.desc": "Facilitate click & collect orders.",
    "sector.restaurants.stat1.value": "+50%",
    "sector.restaurants.stat1.label": "Reservations",
    "sector.restaurants.stat2.value": "0",
    "sector.restaurants.stat2.label": "Missed calls",
    "sector.restaurants.stat3.value": "5min",
    "sector.restaurants.stat3.label": "Average response time",
    "sector.restaurants.video.title": "Botler™ in restaurants",
    "sector.restaurants.testimonial.text": "Our reservations increased by 50% thanks to Botler™'s permanent availability.",
    "sector.restaurants.testimonial.author": "Restaurant Le Gourmet",
    "sector.restaurants.testimonial.role": "Chef owner",

    // Sector Pages - Bakery
    "sector.boulangerie.badge": "Bakery Solution",
    "sector.boulangerie.title1": "Botler™ for",
    "sector.boulangerie.highlight": "Bakeries",
    "sector.boulangerie.description": "The ideal virtual salesperson to present your products and take orders.",
    "sector.boulangerie.challenge1": "Queue that discourages customers",
    "sector.boulangerie.challenge2": "Special orders difficult to manage",
    "sector.boulangerie.challenge3": "Unsold products at end of day",
    "sector.boulangerie.challenges.title1": "Challenges in",
    "sector.boulangerie.challenges.highlight": "bakeries",
    "sector.boulangerie.challenges.description": "Artisan bakeries must combine quality and efficiency.",
    "sector.boulangerie.solutions.title1": "Our",
    "sector.boulangerie.solutions.highlight": "solutions",
    "sector.boulangerie.solution1.title": "Product catalog",
    "sector.boulangerie.solution1.desc": "Present all your breads and pastries.",
    "sector.boulangerie.solution2.title": "Order taking",
    "sector.boulangerie.solution2.desc": "Online orders for in-store pickup.",
    "sector.boulangerie.solution3.title": "Hours and availability",
    "sector.boulangerie.solution3.desc": "Inform about available products in real time.",
    "sector.boulangerie.stat1.value": "+30%",
    "sector.boulangerie.stat1.label": "Online orders",
    "sector.boulangerie.stat2.value": "-20%",
    "sector.boulangerie.stat2.label": "Unsold items",
    "sector.boulangerie.stat3.value": "100%",
    "sector.boulangerie.stat3.label": "Satisfied customers",
    "sector.boulangerie.video.title": "Botler™ in bakeries",
    "sector.boulangerie.testimonial.text": "Online orders increased by 30% and our unsold items decreased by 20%.",
    "sector.boulangerie.testimonial.author": "Corner Bakery",
    "sector.boulangerie.testimonial.role": "Artisan baker",

    // Sector Pages - Real Estate
    "sector.immobilier.badge": "Real Estate Solution",
    "sector.immobilier.title1": "Botler™ for",
    "sector.immobilier.highlight": "Real Estate",
    "sector.immobilier.description": "Your virtual agent to qualify your prospects and present your properties 24/7.",
    "sector.immobilier.challenge1": "Unqualified prospects wasting time",
    "sector.immobilier.challenge2": "Information requests outside office hours",
    "sector.immobilier.challenge3": "Useless visits for unsuitable properties",
    "sector.immobilier.challenges.title1": "Challenges in",
    "sector.immobilier.challenges.highlight": "real estate",
    "sector.immobilier.challenges.description": "Real estate requires responsiveness and precise prospect qualification.",
    "sector.immobilier.solutions.title1": "Our",
    "sector.immobilier.solutions.highlight": "solutions",
    "sector.immobilier.solution1.title": "Prospect qualification",
    "sector.immobilier.solution1.desc": "Identify serious buyers automatically.",
    "sector.immobilier.solution2.title": "Property presentation",
    "sector.immobilier.solution2.desc": "Answer questions about each property.",
    "sector.immobilier.solution3.title": "Appointment booking",
    "sector.immobilier.solution3.desc": "Schedule visits directly in your calendar.",
    "sector.immobilier.stat1.value": "+45%",
    "sector.immobilier.stat1.label": "Qualified contacts",
    "sector.immobilier.stat2.value": "2x",
    "sector.immobilier.stat2.label": "More useful visits",
    "sector.immobilier.stat3.value": "24/7",
    "sector.immobilier.stat3.label": "Availability",
    "sector.immobilier.video.title": "Botler™ in real estate",
    "sector.immobilier.testimonial.text": "Our qualified contacts increased by 45% and our visits are much more effective.",
    "sector.immobilier.testimonial.author": "Immo Plus Agency",
    "sector.immobilier.testimonial.role": "Agency director",

    // Sector Pages - Accommodation
    "sector.hebergements.badge": "Accommodation Solution",
    "sector.hebergements.title1": "Botler™ for",
    "sector.hebergements.highlight": "Accommodation",
    "sector.hebergements.description": "Your virtual concierge to assist your traveling guests before, during and after their stay.",
    "sector.hebergements.challenge1": "Repetitive guest questions (WiFi, check-in...)",
    "sector.hebergements.challenge2": "Requests outside reception hours",
    "sector.hebergements.challenge3": "Difficulty personalizing the guest experience",
    "sector.hebergements.challenges.title1": "Challenges in",
    "sector.hebergements.challenges.highlight": "accommodation",
    "sector.hebergements.challenges.description": "Accommodation requires availability and personalization for each traveler.",
    "sector.hebergements.solutions.title1": "Our",
    "sector.hebergements.solutions.highlight": "solutions",
    "sector.hebergements.solution1.title": "Stay information",
    "sector.hebergements.solution1.desc": "Answer questions about WiFi, parking, check-in...",
    "sector.hebergements.solution2.title": "Available services",
    "sector.hebergements.solution2.desc": "Present breakfast, spa, room service...",
    "sector.hebergements.solution3.title": "Local recommendations",
    "sector.hebergements.solution3.desc": "Suggest restaurants, activities and sites to visit.",
    "sector.hebergements.stat1.value": "+35%",
    "sector.hebergements.stat1.label": "Direct bookings",
    "sector.hebergements.stat2.value": "+40%",
    "sector.hebergements.stat2.label": "Guest satisfaction",
    "sector.hebergements.stat3.value": "90%",
    "sector.hebergements.stat3.label": "Questions resolved",
    "sector.hebergements.video.title": "Botler™ for accommodation",
    "sector.hebergements.testimonial.text": "Botler™ has revolutionized our reception. +40% satisfaction and 24/7 availability.",
    "sector.hebergements.testimonial.author": "Hotel du Phare",
    "sector.hebergements.testimonial.role": "Director",

    // Home Hero Section
    "home.hero.tagline": "Digital transformation is for everyone",
    "home.hero.title1": "Professional digital tools.",
    "home.hero.title2": "At unbeatable",
    "home.hero.title3": "prices.",
    "home.hero.description": "Websites, chatbots, mobile apps, 360° videos, podcasts and custom music - created with AI, delivered in days, accessible to everyone.",
    "home.hero.baseline": "Botler360 is technology without complexity.",
    "home.hero.badge1": "5-minute setup",
    "home.hero.badge2": "Smart automation",
    "home.hero.badge3": "Full customization",
    "home.hero.badge4": "Support team 9am-6pm",
    "home.trust.compatible": "Compatible with Shopify, WordPress, etc.",
    "home.trust.secure": "100% secure, hosted in Europe",
    "home.trust.pme": "Ideal for SMEs",
    "home.hero.cta1": "Watch demos",
    "home.hero.cta2": "Get my chatbot",
    "home.hero.stat": "15 hours",
    "home.hero.statLabel": "saved",
    "home.hero.statSub": "per week",

    // Home Expertises Section (6 Products)
    "home.expertises.title1": "Our",
    "home.expertises.highlight": "expertise",
    "home.expertises.title2": "",
    "home.expertises.description": "6 digital solutions to transform your business",
    "home.expertises.chatbot.title": "Intelligent chatbots",
    "home.expertises.chatbot.desc": "Virtual assistants to respond 24/7, automate and boost your conversions.",
    "home.expertises.chatbot.price": "From €9/month",
    "home.expertises.website.title": "Professional websites",
    "home.expertises.website.desc": "Showcase sites, e-commerce, landing pages... AI-created, SEO & mobile optimized.",
    "home.expertises.website.price": "€249 all included",
    "home.expertises.mobile.title": "Mobile applications",
    "home.expertises.mobile.desc": "iOS & Android apps to manage your business and retain your customers.",
    "home.expertises.mobile.price": "€249",
    "home.expertises.video360.title": "360° immersive videos",
    "home.expertises.video360.desc": "Virtual tours for hotels, restaurants, museums - an immersive experience.",
    "home.expertises.video360.price": "From €125",
    "home.expertises.audio.title": "Music & podcasts",
    "home.expertises.audio.desc": "Custom audio identity: ambient music, announcements, branded podcasts.",
    "home.expertises.audio.price": "From €5",
    "home.expertises.custom.title": "Custom projects",
    "home.expertises.custom.desc": "Dashboards, automations, business tools: we bring your AI idea to life.",
    "home.expertises.custom.price": "Quote",
    "home.expertises.cta": "Learn more",

    // Home Value Pillars Section
    "home.pillars.title1": "Our",
    "home.pillars.highlight": "3 pillars",
    "home.pillars.title2": "of value",
    "home.pillars.speed.title": "Speed",
    "home.pillars.speed.desc": "Our tools are ready in days, not weeks.",
    "home.pillars.simplicity.title": "Simplicity",
    "home.pillars.simplicity.desc": "We make tech simple, even for those who know nothing about it.",
    "home.pillars.accessibility.title": "Accessibility",
    "home.pillars.accessibility.desc": "Because everyone should have access to digital tools, regardless of budget.",

    // Home Stats Section
    "home.stats.title1": "Automate",
    "home.stats.title2": "of your customer responses",
    "home.stats.description": "Free your team from repetitive questions so they can focus on high-value tasks.",
    "home.stats.card.title1": "More than",
    "home.stats.card.title2": "of consumers prefer to interact with a chatbot rather than by phone.",
    "home.stats.card.description": "With Botler™, prevent your visitors from leaving your website because they couldn't quickly get an answer to their questions.",
    "home.stats.card.highlight": "Stop losing 50% of potential customers",
    
    // Home Features Section
    "home.features.title1": "Botler™, the chatbot designed to",
    "home.features.highlight": "boost",
    "home.features.title2": "your customer relationships",
    "home.features.description": "Quickly deploy a conversational assistant on your website and gain efficiency.",
    "home.features.install.title": "5-minute setup",
    "home.features.install.desc": "Quickly deploy a conversational assistant on your website and gain efficiency.",
    "home.features.available.title": "Available 24/7",
    "home.features.available.desc": "Instantly respond to your visitors' questions 24 hours a day, 7 days a week.",
    "home.features.qualify.title": "Automatic qualification",
    "home.features.qualify.desc": "Automatically qualify your prospects and increase your conversions.",
    
    // Home Sectors Section
    "home.sectors.title1": "Solutions",
    "home.sectors.highlight": "tailored",
    "home.sectors.title2": "to your business",
    "home.sectors.description": "Every industry has its own challenges. Botler™ has developed intelligent chatbots that perfectly master the specifics of your field.",
    "home.sectors.botlerSays": "I'm Botler™: want to see what I can do?",
    "home.sectors.viewDemos": "Watch demos",
    "home.sectors.tourism.desc": "Virtual guide for your visitors",
    "home.sectors.tourism.stat": "+40% satisfaction",
    "home.sectors.viticulture.desc": "Virtual sommelier for wine advice",
    "home.sectors.viticulture.stat": "+35% sales",
    "home.sectors.restaurants.desc": "Your best restaurant assistant 24/7",
    "home.sectors.restaurants.stat": "+50% bookings",
    "home.sectors.bakery.desc": "The bakery salesperson you've dreamed of",
    "home.sectors.bakery.stat": "+30% orders",
    "home.sectors.realEstate.desc": "Your virtual agent to better qualify future clients",
    "home.sectors.realEstate.stat": "+45% contacts",
    "home.sectors.accommodation.desc": "Virtual concierge for your guests",
    "home.sectors.accommodation.stat": "+35% bookings",
    
    // Home Testimonials Section
    "home.testimonials.title1": "What our",
    "home.testimonials.highlight": "clients",
    "home.testimonials.title2": "say",
    "home.testimonials.description": "Discover how Botler™ transforms their customer relationships",
    "home.testimonials.1.text": "Botler™ has revolutionized our visitor reception. +40% customer satisfaction and 24/7 availability that makes the difference.",
    "home.testimonials.1.author": "Hotel du Phare",
    "home.testimonials.1.sector": "Accommodation",
    "home.testimonials.1.stat": "+40% customer satisfaction",
    "home.testimonials.2.text": "Our bookings increased by 35% thanks to Botler™'s permanent availability. No more lost opportunities!",
    "home.testimonials.2.author": "Restaurant Le Gourmet",
    "home.testimonials.2.sector": "Restaurant",
    "home.testimonials.2.stat": "+35% bookings",
    "home.testimonials.3.text": "Botler™ saves us 15 hours per week by answering our customers' recurring questions.",
    "home.testimonials.3.author": "Domaine des Vignes",
    "home.testimonials.3.sector": "Viticulture",
    "home.testimonials.3.stat": "15h saved/week",
    
    // CTA Section
    "cta.title1": "Join the companies that have already",
    "cta.highlight": "revolutionized",
    "cta.title2": "their customer relationships with Botler™.",
    "cta.description": "Deploy your chatbot in less than 5 minutes and start improving your customer relationships today.",
    "cta.button": "Get my chatbot",
    
    // Footer
    "footer.description": "Intelligent chatbots tailored to your industry to revolutionize your customer relationships.",
    "footer.company": "Company",
    "footer.location": "France, UK, Tunisia & Indonesia",
    "footer.legal": "Legal Notice",
    "footer.cgv": "Terms & Conditions",
    "footer.privacy": "Privacy Policy",
    "footer.cookies": "Cookie Policy",
    "footer.rights": "All rights reserved.",
    "footer.tagline": "Created with passion to revolutionize your customer relationships.",
    "footer.trust.humanTeam": "Behind our AI tools, there's a human team.",
    "footer.trust.support": "We support you at every step.",
    "footer.trust.location": "Team based in France, UK, Tunisia & Indonesia",
    "footer.trust.ethical": "Ethical and transparent AI",
    "footer.trust.ownership": "You keep 100% ownership of your tools.",
    "footer.trust.smile": "Botler360 is technology with a smile.",
    
    // Demo Page
    "demo.title1": "Discover Botler™",
    "demo.highlight": "in action",
    "demo.description": "Explore our video demonstrations for each industry and discover how Botler™ can transform your customer relationships.",
    "demo.selectSector": "Select a sector",
    "demo.watchVideo": "Watch video",
    "demo.features": "Key features",
    "demo.noVideo": "Video coming soon",
    "demo.categorySectors": "Demos by Sector",
    "demo.categoryProducts": "Demos by Product",
    "demo.allSectorDemos": "All sector demos",
    "demo.allProductDemos": "All product demos",
    "demo.productLabel": "Botler360 Solution",
    "demo.learnMore": "Learn more",
    "demo.tourism.name": "Tourism",
    "demo.tourism.description": "Discover how Botler™ guides your visitors and answers all their questions about your destination.",
    "demo.tourism.feature1": "Personalized recommendations",
    "demo.tourism.feature2": "Multilingual support",
    "demo.tourism.feature3": "Available 24/7",
    "demo.viticulture.name": "Viticulture",
    "demo.viticulture.description": "Your virtual sommelier advises your customers on food-wine pairings and your vintages.",
    "demo.viticulture.feature1": "Wine advice",
    "demo.viticulture.feature2": "Visit booking",
    "demo.viticulture.feature3": "Vintage presentation",
    "demo.restaurants.name": "Restaurants",
    "demo.restaurants.description": "Botler™ manages your reservations and presents your menu to your gourmet customers.",
    "demo.restaurants.feature1": "Reservation management",
    "demo.restaurants.feature2": "Menu presentation",
    "demo.restaurants.feature3": "Allergen information",
    "demo.bakery.name": "Bakery",
    "demo.bakery.description": "The ideal virtual salesperson to present your products and take orders.",
    "demo.bakery.feature1": "Product catalog",
    "demo.bakery.feature2": "Order taking",
    "demo.bakery.feature3": "Hours and availability",
    "demo.realEstate.name": "Real Estate",
    "demo.realEstate.description": "Automatically qualify your prospects and present your properties.",
    "demo.realEstate.feature1": "Prospect qualification",
    "demo.realEstate.feature2": "Property presentation",
    "demo.realEstate.feature3": "Appointment booking",
    "demo.accommodation.name": "Accommodation",
    "demo.accommodation.description": "Your virtual concierge answers your traveling guests' questions.",
    "demo.accommodation.feature1": "Stay information",
    "demo.accommodation.feature2": "Available services",
    "demo.accommodation.feature3": "Local recommendations",
    "demo.boutiques.name": "Shops & Retail",
    "demo.boutiques.description": "Discover how Botler™ assists your in-store customers and boosts your sales.",
    "demo.boutiques.feature1": "Interactive product catalog",
    "demo.boutiques.feature2": "Automated click & collect",
    "demo.boutiques.feature3": "Integrated loyalty program",
    "demo.websites.name": "Professional Websites",
    "demo.websites.description": "Explore our turnkey websites with integrated chatbot to convert your visitors.",
    "demo.websites.fullDescription": "Discover how Botler360 creates modern showcase websites, SEO-optimized and delivered turnkey in just a few days for only €249. Ideal for freelancers, artisans, and SMEs.",
    "demo.websites.feature1": "Modern responsive design",
    "demo.websites.feature2": "Free integrated chatbot",
    "demo.websites.feature3": "SEO optimization included",
    "demo.websites.feature4": "Hosting and maintenance included",
    "demo.ecommerce.name": "E-commerce Stores",
    "demo.ecommerce.description": "See how our solutions let you sell your products online easily, with inventory management, secure payment, and an optimized customer experience.",
    "demo.ecommerce.feature1": "Secure online payment",
    "demo.ecommerce.feature2": "Integrated inventory management",
    "demo.ecommerce.feature3": "Click & Collect available",
    "demo.ecommerce.feature4": "Chatbot-assisted sales",
    "demo.stats.clients": "Satisfied clients",
    "demo.stats.hours": "Customer service saved",
    "demo.stats.satisfaction": "Customer satisfaction",
    
    // Solutions Page
    "solutions.title1": "Our",
    "solutions.highlight": "Digital Solutions",
    "solutions.description": "Develop your online presence with our custom solutions, designed to boost your business.",
    "solutions.pricing.title1": "Chatbot",
    "solutions.pricing.highlight": "Pricing",
    "solutions.pricing.subtitle": "Transparent pricing tailored to your needs",
    "solutions.pricing.perMonth": "/month",
    "solutions.pricing.recommended": "Recommended",
    "solutions.pricing.commission": "1% commission on each sale made entirely with Botler (Expert and Expert SME packs)",
    
    // Pack Junior
    "solutions.pricing.junior.desc": "For all types of businesses",
    "solutions.pricing.junior.f1": "Quick installation",
    "solutions.pricing.junior.f2": "Customized to your brand identity",
    "solutions.pricing.junior.f3": "Custom responses to visitor questions",
    "solutions.pricing.junior.f4": "Multi-language support",
    "solutions.pricing.junior.cta": "Get Started",
    
    // Pack Expert
    "solutions.pricing.expert.desc": "Perfect for freelancers and micro-teams",
    "solutions.pricing.expert.f1": "Smart matching on targeted database",
    "solutions.pricing.expert.f2": "Simple and quick installation",
    "solutions.pricing.expert.f3": "Customized to your brand identity",
    "solutions.pricing.expert.f4": "Integrated sales assistant (leads, email alerts, appointments)",
    "solutions.pricing.expert.f5": "Multilingual",
    "solutions.pricing.expert.f6": "Turnkey solution to generate your first leads",
    "solutions.pricing.expert.cta": "Choose Expert",
    
    // Pack Expert PME
    "solutions.pricing.expertPME.desc": "Designed for growing SMEs",
    "solutions.pricing.expertPME.f1": "Built for small and medium businesses",
    "solutions.pricing.expertPME.f2": "Smart filtering + advanced matching",
    "solutions.pricing.expertPME.f3": "Optimized for large content volumes",
    "solutions.pricing.expertPME.f4": "Customized to your image and multilingual",
    "solutions.pricing.expertPME.f5": "Sales assistant with alerts and auto lead creation",
    "solutions.pricing.expertPME.f6": "Robust bot to handle high volume of requests",
    "solutions.pricing.expertPME.cta": "Choose Expert SME",
    
    // Pack Custom
    "solutions.pricing.custom.name": "Specific request or need?",
    "solutions.pricing.custom.price": "Quote",
    "solutions.pricing.custom.desc": "Custom solution based on your specific needs",
    "solutions.pricing.custom.f1": "Tailored support",
    "solutions.pricing.custom.f2": "Advanced features à la carte",
    "solutions.pricing.custom.cta": "Contact us",
    "solutions.guarantees.satisfaction.title": "Satisfaction guaranteed",
    "solutions.guarantees.satisfaction.desc": "30-day free trial",
    "solutions.guarantees.deploy.title": "Fast deployment",
    "solutions.guarantees.deploy.desc": "Online within 24 hours",
    "solutions.guarantees.support.title": "Expert support",
    "solutions.guarantees.support.desc": "Team dedicated to your success",
    "solutions.website.badge": "Special Offer",
    "solutions.website.title": "Professional Showcase Website",
    "solutions.website.description": "A complete solution to create your professional online presence quickly and efficiently.",
    "solutions.website.h1": "24h delivery",
    "solutions.website.h2": "Responsive design",
    "solutions.website.h3": "Hosting included",
    "solutions.website.h4": "Mobile compatible",
    "solutions.website.f1": "Modern responsive design",
    "solutions.website.f2": "Secure web hosting",
    "solutions.website.f3": "Free SSL certificate",
    "solutions.website.f4": "Basic SEO optimization",
    "solutions.website.f5": "Contact form",
    "solutions.website.f6": "Social media integration",
    "solutions.website.f7": "30-day technical support",
    "solutions.website.f8": "Usage training",
    "solutions.website.f9": "Automatic backup",
    "solutions.website.f10": "Visit statistics",
    "solutions.website.included": "What's included",
    "solutions.website.cta": "Order now",
    "solutions.additional.title1": "Other",
    "solutions.additional.highlight": "Solutions",
    "solutions.additional.description": "Complete your digital presence with our additional services",
    "solutions.additional.mobile.title": "Mobile Application",
    "solutions.additional.mobile.desc": "Custom iOS and Android app for your business",
    "solutions.additional.video360.title": "360° Immersive Videos",
    "solutions.additional.video360.desc": "Virtual tours for hotels, restaurants, museums - an immersive experience",
    "solutions.additional.video360.price": "Starting at €125",
    "solutions.additional.audio.title": "Music & Podcasts",
    "solutions.additional.audio.desc": "Custom audio identity: ambient music, announcements, branded podcasts",
    "solutions.additional.audio.price": "Starting at €5",
    "solutions.additional.custom.title": "Custom Projects",
    "solutions.additional.custom.desc": "Dashboards, automations, business tools: we bring your AI idea to life.",
    "solutions.additional.custom.price": "Quote",

    // Websites Page
    "websites.badge": "Professional Website",
    "websites.title1": "Your professional website.",
    "websites.highlight": "Turnkey.",
    "websites.title2": "€249 all included... for life.",
    "websites.description": "A modern website, SEO and mobile optimized, AI-created and delivered in 24-48h.",
    "websites.priceLabel": "all included, one-time payment",
    "websites.highlight1": "24-48h delivery",
    "websites.highlight2": "Responsive design",
    "websites.highlight3": "Hosting included",
    "websites.highlight4": "Mobile compatible",
    "websites.cta": "Order my website",
    "websites.bonus.title": "Bonus: Free integrated chatbot for the first month!",
    "websites.bonus.description": "Each website includes a free Botler™ chatbot for 30 days to boost your conversions.",
    "websites.points.title1": "Why choose",
    "websites.points.highlight": "Botler360?",
    "websites.point1.title": "Stop hiding",
    "websites.point1.desc": "Finally have a professional online presence that represents you.",
    "websites.point2.title": "Be visible",
    "websites.point2.desc": "SEO-optimized site to be found on Google by your future customers.",
    "websites.point3.title": "Create opportunities",
    "websites.point3.desc": "Turn visitors into customers with a converting website.",
    "websites.point4.title": "Zero effort",
    "websites.point4.desc": "We handle everything: design, development, hosting, maintenance.",
    "websites.features.title": "Everything included",
    "websites.feature1": "Modern responsive design",
    "websites.feature2": "Secure web hosting",
    "websites.feature3": "Free SSL certificate (HTTPS)",
    "websites.feature4": "Basic SEO optimization",
    "websites.feature5": "Contact form",
    "websites.feature6": "Social media integration",
    "websites.feature7": "30-day technical support",
    "websites.feature8": "Usage training",
    "websites.feature9": "Automatic backup",
    "websites.feature10": "Visit statistics",
    "websites.compare.title1": "Compare and",
    "websites.compare.highlight": "save",
    "websites.compare.price": "Price",
    "websites.compare.delivery": "Delivery",
    "websites.compare.hosting": "Hosting included",
    "websites.compare.seo": "SEO optimization",
    "websites.compare.support": "Support",
    "websites.compare.chatbot": "Integrated chatbot",
    "websites.compare.diy": "DIY",
    "websites.compare.free1month": "1 month free",
    "websites.cta.title1": "Ready to launch",
    "websites.cta.highlight": "your site?",
    "websites.cta.description": "Order now and receive your professional website in 24-48h.",
    "websites.cta.button": "Order now",

    // Mobile Apps Page
    "mobileapps.badge": "Mobile Application",
    "mobileapps.title1": "Your mobile app,",
    "mobileapps.highlight": "ready in 7 days.",
    "mobileapps.title2": "For only €249.",
    "mobileapps.description": "A custom iOS & Android app to manage your business and retain your customers.",
    "mobileapps.priceLabel": "all included",
    "mobileapps.highlight1": "iOS & Android",
    "mobileapps.highlight2": "7-day delivery",
    "mobileapps.highlight3": "Store publication",
    "mobileapps.highlight4": "Custom design",
    "mobileapps.cta": "Order my app",
    "mobileapps.points.title1": "Why a",
    "mobileapps.points.highlight": "mobile app?",
    "mobileapps.point1.title": "The cheapest app",
    "mobileapps.point1.desc": "€249 instead of €5000+ at a traditional agency.",
    "mobileapps.point2.title": "Express delivery",
    "mobileapps.point2.desc": "Your app ready in 7 days, not several months.",
    "mobileapps.point3.title": "Total transparency",
    "mobileapps.point3.desc": "Fixed price, no surprises or hidden fees.",
    "mobileapps.point4.title": "Zero risk",
    "mobileapps.point4.desc": "Satisfied or refunded for 30 days.",
    "mobileapps.features.title": "13 features included",
    "mobileapps.feature1": "Custom design to your image",
    "mobileapps.feature2": "iOS and Android compatible",
    "mobileapps.feature3": "Push notifications",
    "mobileapps.feature4": "Product/service catalog",
    "mobileapps.feature5": "Booking system",
    "mobileapps.feature6": "Loyalty program",
    "mobileapps.feature7": "Integrated online payment",
    "mobileapps.feature8": "Integrated messaging",
    "mobileapps.feature9": "Geolocation",
    "mobileapps.feature10": "Offline mode",
    "mobileapps.feature11": "Usage statistics",
    "mobileapps.feature12": "Free updates 1 year",
    "mobileapps.feature13": "Dedicated technical support",
    "mobileapps.process.title1": "A simple",
    "mobileapps.process.highlight": "3-step process",
    "mobileapps.process.step1.title": "1. Briefing",
    "mobileapps.process.step1.desc": "You describe your needs and visual identity.",
    "mobileapps.process.step2.title": "2. Development",
    "mobileapps.process.step2.desc": "Our team creates your app with AI in 5-7 days.",
    "mobileapps.process.step3.title": "3. Delivery",
    "mobileapps.process.step3.desc": "Publication on App Store and Google Play included.",
    "mobileapps.faq.title": "Frequently asked questions",
    "mobileapps.faq.q1": "Is the app really mine?",
    "mobileapps.faq.a1": "Yes, you are 100% owner of your application.",
    "mobileapps.faq.q2": "What are the recurring fees?",
    "mobileapps.faq.a2": "No hidden fees. Only store fees (Apple €99/year, Google €25 once) apply.",
    "mobileapps.faq.q3": "Can I modify the app after delivery?",
    "mobileapps.faq.a3": "Yes, content updates are free for 1 year.",
    "mobileapps.faq.q4": "How does support work?",
    "mobileapps.faq.a4": "You benefit from dedicated technical support by email for 1 year.",
    "mobileapps.cta.title1": "Ready to launch",
    "mobileapps.cta.highlight": "your app?",
    "mobileapps.cta.description": "Order now and receive your application in 7 days.",
    "mobileapps.cta.button": "Order now",

    // FAQ Page
    "faq.title1": "Frequently",
    "faq.highlight": "Asked Questions",
    "faq.description": "Find answers to the most common questions about our chatbots and website creation services.",
    "faq.categoryChatbots": "Chatbots FAQ",
    "faq.categoryWebsites": "Websites FAQ",
    "faq.cta.title": "Didn't find your answer?",
    "faq.cta.description": "Our team is here to help. Contact us and we'll answer all your questions.",
    "faq.cta.button": "Contact us",

    // Contact Page
    "contact.title1": "Contact",
    "contact.highlight": "our team",
    "contact.description": "Let's discuss your project and discover how Botler™ can transform your customer relationships.",
    "contact.form.title": "Send us a message",
    "contact.form.firstName": "First name",
    "contact.form.firstNamePlaceholder": "Your first name",
    "contact.form.lastName": "Last name",
    "contact.form.lastNamePlaceholder": "Your last name",
    "contact.form.optional": "optional",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "your@email.com",
    "contact.form.company": "Company",
    "contact.form.companyPlaceholder": "Your company name",
    "contact.form.sector": "Industry",
    "contact.form.sectorPlaceholder": "Select a sector",
    "contact.form.other": "Other",
    "contact.form.projectType": "Project Type",
    "contact.form.projectTypePlaceholder": "Select a project type",
    "contact.form.projectType.chatbot": "Chatbot",
    "contact.form.projectType.website": "Website",
    "contact.form.projectType.websiteChatbot": "Website + Chatbot",
    "contact.form.projectType.mobileApp": "Mobile Application",
    "contact.form.projectType.video360": "360° Video",
    "contact.form.projectType.musicPodcast": "Music / Podcast",
    "contact.form.projectType.custom": "Custom Project",
    "contact.form.phone": "Phone",
    "contact.form.phonePlaceholder": "+33 6 00 00 00 00",
    "contact.form.attachment": "Attach a file",
    "contact.form.attachmentPlaceholder": "Upload a file (PDF, DOC, image)",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Describe your project...",
    "contact.form.submit": "Send message",
    "contact.form.sending": "Sending...",
    "contact.form.success": "Message sent successfully! We'll respond within 24 hours.",
    "contact.form.error": "An error occurred. Please try again.",
    "contact.form.surpriseMe": "Surprise me!",
    "contact.form.surpriseSuccess": "Request sent! Our team will prepare a custom proposal for you.",
    "contact.form.fileTooLarge": "File is too large (max 10 MB).",
    "contact.info.title": "Our contact details",
    "contact.info.phone": "Phone",
    "contact.info.email": "Email",
    "contact.info.location": "Location",
    "contact.benefits.title": "Why contact us?",
    "contact.benefits.fast.title": "Quick response",
    "contact.benefits.fast.desc": "Our team responds within 24 hours",
    "contact.benefits.personal.title": "Personalized support",
    "contact.benefits.personal.desc": "An expert dedicated to your project",
    "contact.benefits.free.title": "Free quote",
    "contact.benefits.free.desc": "No commitment required",
    "contact.mascot": "Our team is here to support you in your digital transformation.",

    // Chat Widget
    "chat.button": "Talk to Botler",
    "chat.online": "online",
    "chat.placeholder": "Type your message...",
    "chat.poweredBy": "Powered by Botler 360",
    "chat.welcome.title": "Hello! I'm Botler 👋",
    "chat.welcome.text": "How can I help you today?",

    // SEO
    "seo.home.title": "AI Chatbot for SMBs",
    "seo.home.description": "Botler, the AI chatbot for small and medium businesses. Deploy an intelligent assistant on your website in minutes.",
    "seo.demo.title": "Chatbot Demo",
    "seo.demo.description": "See Botler in action. Try our AI chatbots for tourism, restaurants, real estate and more.",
    "seo.contact.title": "Contact",
    "seo.contact.description": "Contact the Botler 360 team. We respond within 24 hours to discuss your chatbot or website project.",
    "seo.solutions.title": "Our Solutions and Pricing",
    "seo.solutions.description": "Discover our AI chatbot plans from 29€/month. Websites at 249€. Custom solutions for every business.",
    "seo.faq.title": "FAQ",
    "seo.faq.description": "All your questions about AI chatbots and website creation. Clear and detailed answers.",
    "seo.websites.title": "Website Creation",
    "seo.websites.description": "Professional website at 249€. Modern design, SEO optimized, with integrated AI chatbot.",
    "seo.mobileapps.title": "Mobile Applications",
    "seo.mobileapps.description": "iOS and Android mobile app at 249€. Fast, performant, with all essential features.",
    "seo.sector.tourisme.title": "AI Chatbot for Tourism",
    "seo.sector.tourisme.description": "Tourism-specialized AI chatbot. Answer travelers 24/7, manage bookings and qualify leads.",
    "seo.sector.viticulture.title": "AI Chatbot for Wineries",
    "seo.sector.viticulture.description": "AI chatbot for wineries. Welcome visitors, manage tastings and sell online.",
    "seo.sector.restaurants.title": "AI Chatbot for Restaurants",
    "seo.sector.restaurants.description": "AI chatbot for restaurants. Manage reservations, answer questions and retain customers.",
    "seo.sector.boulangerie.title": "AI Chatbot for Bakeries",
    "seo.sector.boulangerie.description": "AI chatbot for bakeries. Online orders, hours, and automated customer service.",
    "seo.sector.immobilier.title": "AI Chatbot for Real Estate",
    "seo.sector.immobilier.description": "AI chatbot for real estate agencies. Qualify buyers, schedule visits and respond 24/7.",
    "seo.sector.hebergements.title": "AI Chatbot for Hotels",
    "seo.sector.hebergements.description": "AI chatbot for hotels and accommodations. Bookings, concierge and automated customer service.",

    // Legal Pages
    "legal.mentions.title": "Legal Notice",
    "legal.mentions.editor.title": "Website Publisher",
    "legal.mentions.host.title": "Host",
    "legal.mentions.ip.title": "Intellectual Property",
    "legal.mentions.liability.title": "Liability",
    "legal.mentions.data.title": "Personal Data",
    "legal.mentions.law.title": "Applicable Law",
    "legal.cgv.title": "Terms and Conditions",
    "legal.cgv.article1.title": "Article 1 — Purpose",
    "legal.cgv.article2.title": "Article 2 — Acceptance of Terms",
    "legal.cgv.article3.title": "Article 3 — Description of Services",
    "legal.cgv.article4.title": "Article 4 — Pricing and Payment",
    "legal.cgv.article5.title": "Article 5 — Duration and Termination",
    "legal.cgv.article6.title": "Article 6 — Intellectual Property",
    "legal.cgv.article7.title": "Article 7 — Liability and Warranties",
    "legal.cgv.article8.title": "Article 8 — Personal Data",
    "legal.cgv.article9.title": "Article 9 — Right of Withdrawal",
    "legal.cgv.article10.title": "Article 10 — Disputes",
    "legal.privacy.title": "Privacy Policy",
    "legal.privacy.controller.title": "Data Controller",
    "legal.privacy.collected.title": "Data Collected",
    "legal.privacy.purposes.title": "Processing Purposes",
    "legal.privacy.legal-basis.title": "Legal Basis",
    "legal.privacy.recipients.title": "Data Recipients",
    "legal.privacy.retention.title": "Retention Period",
    "legal.privacy.rights.title": "Your Rights",
    "legal.privacy.cookies.title": "Cookies",
    "legal.privacy.transfers.title": "Transfers Outside EU",
    "legal.privacy.dpo.title": "DPO Contact",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("botler-language");
      if (saved === "en" || saved === "fr") return saved;
    }
    return "fr";
  });

  useEffect(() => {
    localStorage.setItem("botler-language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
